/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/_terminal'
import { Route as TerminalIndexRouteImport } from './routes/_terminal.index'
import { Route as TerminalSettingsRouteImport } from './routes/_terminal.settings'
import { Route as TerminalCheckoutRouteImport } from './routes/_terminal.checkout'
import { Route as TerminalActivityRouteImport } from './routes/_terminal.activity'
import { Route as TerminalSettingsIndexRouteImport } from './routes/_terminal.settings.index'
import { Route as TerminalSettingsThemeRouteImport } from './routes/_terminal.settings.theme'
import { Route as TerminalSettingsLanguageRouteImport } from './routes/_terminal.settings.language'
import { Route as TerminalSettingsItemsRouteImport } from './routes/_terminal.settings.items'
import { Route as TerminalItemsEditRouteImport } from './routes/_terminal.items.edit'
import { Route as TerminalActivityPaymentIdRouteImport } from './routes/_terminal.activity_.$paymentId'

const TerminalRoute = TerminalRouteImport.update({
  id: '/_terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalSettingsRoute = TerminalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalCheckoutRoute = TerminalCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalActivityRoute = TerminalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalSettingsIndexRoute = TerminalSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsThemeRoute = TerminalSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsLanguageRoute =
  TerminalSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsItemsRoute = TerminalSettingsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalItemsEditRoute = TerminalItemsEditRouteImport.update({
  id: '/items/edit',
  path: '/items/edit',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalActivityPaymentIdRoute =
  TerminalActivityPaymentIdRouteImport.update({
    id: '/activity_/$paymentId',
    path: '/activity/$paymentId',
    getParentRoute: () => TerminalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof TerminalIndexRoute
  '/activity': typeof TerminalActivityRoute
  '/checkout': typeof TerminalCheckoutRoute
  '/settings': typeof TerminalSettingsRouteWithChildren
  '/activity/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/items/edit': typeof TerminalItemsEditRoute
  '/settings/items': typeof TerminalSettingsItemsRoute
  '/settings/language': typeof TerminalSettingsLanguageRoute
  '/settings/theme': typeof TerminalSettingsThemeRoute
  '/settings/': typeof TerminalSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/activity': typeof TerminalActivityRoute
  '/checkout': typeof TerminalCheckoutRoute
  '/': typeof TerminalIndexRoute
  '/activity/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/items/edit': typeof TerminalItemsEditRoute
  '/settings/items': typeof TerminalSettingsItemsRoute
  '/settings/language': typeof TerminalSettingsLanguageRoute
  '/settings/theme': typeof TerminalSettingsThemeRoute
  '/settings': typeof TerminalSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_terminal': typeof TerminalRouteWithChildren
  '/_terminal/activity': typeof TerminalActivityRoute
  '/_terminal/checkout': typeof TerminalCheckoutRoute
  '/_terminal/settings': typeof TerminalSettingsRouteWithChildren
  '/_terminal/': typeof TerminalIndexRoute
  '/_terminal/activity_/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/_terminal/items/edit': typeof TerminalItemsEditRoute
  '/_terminal/settings/items': typeof TerminalSettingsItemsRoute
  '/_terminal/settings/language': typeof TerminalSettingsLanguageRoute
  '/_terminal/settings/theme': typeof TerminalSettingsThemeRoute
  '/_terminal/settings/': typeof TerminalSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/checkout'
    | '/settings'
    | '/activity/$paymentId'
    | '/items/edit'
    | '/settings/items'
    | '/settings/language'
    | '/settings/theme'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/checkout'
    | '/'
    | '/activity/$paymentId'
    | '/items/edit'
    | '/settings/items'
    | '/settings/language'
    | '/settings/theme'
    | '/settings'
  id:
    | '__root__'
    | '/_terminal'
    | '/_terminal/activity'
    | '/_terminal/checkout'
    | '/_terminal/settings'
    | '/_terminal/'
    | '/_terminal/activity_/$paymentId'
    | '/_terminal/items/edit'
    | '/_terminal/settings/items'
    | '/_terminal/settings/language'
    | '/_terminal/settings/theme'
    | '/_terminal/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TerminalRoute: typeof TerminalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_terminal': {
      id: '/_terminal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal/': {
      id: '/_terminal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings': {
      id: '/_terminal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TerminalSettingsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/checkout': {
      id: '/_terminal/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof TerminalCheckoutRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity': {
      id: '/_terminal/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof TerminalActivityRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings/': {
      id: '/_terminal/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof TerminalSettingsIndexRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/theme': {
      id: '/_terminal/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof TerminalSettingsThemeRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/language': {
      id: '/_terminal/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof TerminalSettingsLanguageRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/items': {
      id: '/_terminal/settings/items'
      path: '/items'
      fullPath: '/settings/items'
      preLoaderRoute: typeof TerminalSettingsItemsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/items/edit': {
      id: '/_terminal/items/edit'
      path: '/items/edit'
      fullPath: '/items/edit'
      preLoaderRoute: typeof TerminalItemsEditRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity_/$paymentId': {
      id: '/_terminal/activity_/$paymentId'
      path: '/activity/$paymentId'
      fullPath: '/activity/$paymentId'
      preLoaderRoute: typeof TerminalActivityPaymentIdRouteImport
      parentRoute: typeof TerminalRoute
    }
  }
}

interface TerminalSettingsRouteChildren {
  TerminalSettingsItemsRoute: typeof TerminalSettingsItemsRoute
  TerminalSettingsLanguageRoute: typeof TerminalSettingsLanguageRoute
  TerminalSettingsThemeRoute: typeof TerminalSettingsThemeRoute
  TerminalSettingsIndexRoute: typeof TerminalSettingsIndexRoute
}

const TerminalSettingsRouteChildren: TerminalSettingsRouteChildren = {
  TerminalSettingsItemsRoute: TerminalSettingsItemsRoute,
  TerminalSettingsLanguageRoute: TerminalSettingsLanguageRoute,
  TerminalSettingsThemeRoute: TerminalSettingsThemeRoute,
  TerminalSettingsIndexRoute: TerminalSettingsIndexRoute,
}

const TerminalSettingsRouteWithChildren =
  TerminalSettingsRoute._addFileChildren(TerminalSettingsRouteChildren)

interface TerminalRouteChildren {
  TerminalActivityRoute: typeof TerminalActivityRoute
  TerminalCheckoutRoute: typeof TerminalCheckoutRoute
  TerminalSettingsRoute: typeof TerminalSettingsRouteWithChildren
  TerminalIndexRoute: typeof TerminalIndexRoute
  TerminalActivityPaymentIdRoute: typeof TerminalActivityPaymentIdRoute
  TerminalItemsEditRoute: typeof TerminalItemsEditRoute
}

const TerminalRouteChildren: TerminalRouteChildren = {
  TerminalActivityRoute: TerminalActivityRoute,
  TerminalCheckoutRoute: TerminalCheckoutRoute,
  TerminalSettingsRoute: TerminalSettingsRouteWithChildren,
  TerminalIndexRoute: TerminalIndexRoute,
  TerminalActivityPaymentIdRoute: TerminalActivityPaymentIdRoute,
  TerminalItemsEditRoute: TerminalItemsEditRoute,
}

const TerminalRouteWithChildren = TerminalRoute._addFileChildren(
  TerminalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TerminalRoute: TerminalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
