/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/_terminal'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RestoreAccountRouteImport } from './routes/restore-account'
import { Route as TerminalIndexRouteImport } from './routes/_terminal.index'
import { Route as TerminalActivityRouteImport } from './routes/_terminal.activity'
import { Route as TerminalBillRouteImport } from './routes/_terminal.bill'
import { Route as TerminalSettingsRouteImport } from './routes/_terminal.settings'
import { Route as TerminalActivityPaymentIdRouteImport } from './routes/_terminal.activity_.$paymentId'
import { Route as TerminalPaymentTipRouteImport } from './routes/_terminal.payment.tip'
import { Route as TerminalPaymentPaymentIdRouteImport } from './routes/_terminal.payment_.$paymentId'
import { Route as TerminalSettingsIndexRouteImport } from './routes/_terminal.settings.index'
import { Route as TerminalSettingsAboutRouteImport } from './routes/_terminal.settings.about'
import { Route as TerminalSettingsAccountsRouteImport } from './routes/_terminal.settings.accounts'
import { Route as TerminalSettingsCategoriesRouteImport } from './routes/_terminal.settings.categories'
import { Route as TerminalSettingsDebugConsoleRouteImport } from './routes/_terminal.settings.debug-console'
import { Route as TerminalSettingsDefaultPaymentMethodRouteImport } from './routes/_terminal.settings.default-payment-method'
import { Route as TerminalSettingsDonationsRouteImport } from './routes/_terminal.settings.donations'
import { Route as TerminalSettingsDonationsInvoiceRouteImport } from './routes/_terminal.settings.donations-invoice'
import { Route as TerminalSettingsEvoluExportRouteImport } from './routes/_terminal.settings.evolu-export'
import { Route as TerminalSettingsFiatRouteImport } from './routes/_terminal.settings.fiat'
import { Route as TerminalSettingsFioPluginRouteImport } from './routes/_terminal.settings.fio-plugin'
import { Route as TerminalSettingsItemsRouteImport } from './routes/_terminal.settings.items'
import { Route as TerminalSettingsLanguageRouteImport } from './routes/_terminal.settings.language'
import { Route as TerminalSettingsPaymentAccountsRouteImport } from './routes/_terminal.settings.payment-accounts'
import { Route as TerminalSettingsPaymentNumberSeriesRouteImport } from './routes/_terminal.settings.payment-number-series'
import { Route as TerminalSettingsPrivacyRouteImport } from './routes/_terminal.settings.privacy'
import { Route as TerminalSettingsSecurityRouteImport } from './routes/_terminal.settings.security'
import { Route as TerminalSettingsTablesRouteImport } from './routes/_terminal.settings.tables'
import { Route as TerminalSettingsThemeRouteImport } from './routes/_terminal.settings.theme'
import { Route as TerminalSettingsTipsRouteImport } from './routes/_terminal.settings.tips'
import { Route as TerminalSettingsWithdrawRouteImport } from './routes/_terminal.settings.withdraw'
import { Route as TerminalSettingsAboutIndexRouteImport } from './routes/_terminal.settings.about.index'
import { Route as TerminalSettingsAboutPrivacyRouteImport } from './routes/_terminal.settings.about.privacy'
import { Route as TerminalSettingsAboutTermsRouteImport } from './routes/_terminal.settings.about.terms'
import { Route as TerminalSettingsCategoriesIndexRouteImport } from './routes/_terminal.settings.categories.index'
import { Route as TerminalSettingsCategoriesCatalogCategoryIdRouteImport } from './routes/_terminal.settings.categories.$catalogCategoryId'
import { Route as TerminalSettingsCategoriesNewRouteImport } from './routes/_terminal.settings.categories.new'
import { Route as TerminalSettingsItemsIndexRouteImport } from './routes/_terminal.settings.items.index'
import { Route as TerminalSettingsItemsCatalogItemIdRouteImport } from './routes/_terminal.settings.items.$catalogItemId'
import { Route as TerminalSettingsItemsNewRouteImport } from './routes/_terminal.settings.items.new'
import { Route as TerminalSettingsTablesIndexRouteImport } from './routes/_terminal.settings.tables.index'
import { Route as TerminalSettingsTablesTableIdRouteImport } from './routes/_terminal.settings.tables.$tableId'
import { Route as TerminalSettingsTablesNewRouteImport } from './routes/_terminal.settings.tables.new'

const TerminalRoute = TerminalRouteImport.update({
  id: '/_terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreAccountRoute = RestoreAccountRouteImport.update({
  id: '/restore-account',
  path: '/restore-account',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalActivityRoute = TerminalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalBillRoute = TerminalBillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalSettingsRoute = TerminalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalActivityPaymentIdRoute =
  TerminalActivityPaymentIdRouteImport.update({
    id: '/activity_/$paymentId',
    path: '/activity/$paymentId',
    getParentRoute: () => TerminalRoute,
  } as any)
const TerminalPaymentTipRoute = TerminalPaymentTipRouteImport.update({
  id: '/payment/tip',
  path: '/payment/tip',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalPaymentPaymentIdRoute =
  TerminalPaymentPaymentIdRouteImport.update({
    id: '/payment_/$paymentId',
    path: '/payment/$paymentId',
    getParentRoute: () => TerminalRoute,
  } as any)
const TerminalSettingsIndexRoute = TerminalSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsAboutRoute = TerminalSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsAccountsRoute =
  TerminalSettingsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsCategoriesRoute =
  TerminalSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDebugConsoleRoute =
  TerminalSettingsDebugConsoleRouteImport.update({
    id: '/debug-console',
    path: '/debug-console',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDefaultPaymentMethodRoute =
  TerminalSettingsDefaultPaymentMethodRouteImport.update({
    id: '/default-payment-method',
    path: '/default-payment-method',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDonationsRoute =
  TerminalSettingsDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDonationsInvoiceRoute =
  TerminalSettingsDonationsInvoiceRouteImport.update({
    id: '/donations-invoice',
    path: '/donations-invoice',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsEvoluExportRoute =
  TerminalSettingsEvoluExportRouteImport.update({
    id: '/evolu-export',
    path: '/evolu-export',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsFiatRoute = TerminalSettingsFiatRouteImport.update({
  id: '/fiat',
  path: '/fiat',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsFioPluginRoute =
  TerminalSettingsFioPluginRouteImport.update({
    id: '/fio-plugin',
    path: '/fio-plugin',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsItemsRoute = TerminalSettingsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsLanguageRoute =
  TerminalSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsPaymentAccountsRoute =
  TerminalSettingsPaymentAccountsRouteImport.update({
    id: '/payment-accounts',
    path: '/payment-accounts',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsPaymentNumberSeriesRoute =
  TerminalSettingsPaymentNumberSeriesRouteImport.update({
    id: '/payment-number-series',
    path: '/payment-number-series',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsPrivacyRoute = TerminalSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsSecurityRoute =
  TerminalSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsTablesRoute = TerminalSettingsTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsThemeRoute = TerminalSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsTipsRoute = TerminalSettingsTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsWithdrawRoute =
  TerminalSettingsWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsAboutIndexRoute =
  TerminalSettingsAboutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsAboutRoute,
  } as any)
const TerminalSettingsAboutPrivacyRoute =
  TerminalSettingsAboutPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => TerminalSettingsAboutRoute,
  } as any)
const TerminalSettingsAboutTermsRoute =
  TerminalSettingsAboutTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => TerminalSettingsAboutRoute,
  } as any)
const TerminalSettingsCategoriesIndexRoute =
  TerminalSettingsCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsCategoriesRoute,
  } as any)
const TerminalSettingsCategoriesCatalogCategoryIdRoute =
  TerminalSettingsCategoriesCatalogCategoryIdRouteImport.update({
    id: '/$catalogCategoryId',
    path: '/$catalogCategoryId',
    getParentRoute: () => TerminalSettingsCategoriesRoute,
  } as any)
const TerminalSettingsCategoriesNewRoute =
  TerminalSettingsCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsCategoriesRoute,
  } as any)
const TerminalSettingsItemsIndexRoute =
  TerminalSettingsItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsItemsRoute,
  } as any)
const TerminalSettingsItemsCatalogItemIdRoute =
  TerminalSettingsItemsCatalogItemIdRouteImport.update({
    id: '/$catalogItemId',
    path: '/$catalogItemId',
    getParentRoute: () => TerminalSettingsItemsRoute,
  } as any)
const TerminalSettingsItemsNewRoute =
  TerminalSettingsItemsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsItemsRoute,
  } as any)
const TerminalSettingsTablesIndexRoute =
  TerminalSettingsTablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsTablesRoute,
  } as any)
const TerminalSettingsTablesTableIdRoute =
  TerminalSettingsTablesTableIdRouteImport.update({
    id: '/$tableId',
    path: '/$tableId',
    getParentRoute: () => TerminalSettingsTablesRoute,
  } as any)
const TerminalSettingsTablesNewRoute =
  TerminalSettingsTablesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsTablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof TerminalIndexRoute
  '/error': typeof ErrorRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/restore-account': typeof RestoreAccountRoute
  '/activity': typeof TerminalActivityRoute
  '/bill': typeof TerminalBillRoute
  '/settings': typeof TerminalSettingsRouteWithChildren
  '/activity/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/payment/tip': typeof TerminalPaymentTipRoute
  '/payment/$paymentId': typeof TerminalPaymentPaymentIdRoute
  '/settings/about': typeof TerminalSettingsAboutRouteWithChildren
  '/settings/accounts': typeof TerminalSettingsAccountsRoute
  '/settings/categories': typeof TerminalSettingsCategoriesRouteWithChildren
  '/settings/debug-console': typeof TerminalSettingsDebugConsoleRoute
  '/settings/default-payment-method': typeof TerminalSettingsDefaultPaymentMethodRoute
  '/settings/donations': typeof TerminalSettingsDonationsRoute
  '/settings/donations-invoice': typeof TerminalSettingsDonationsInvoiceRoute
  '/settings/evolu-export': typeof TerminalSettingsEvoluExportRoute
  '/settings/fiat': typeof TerminalSettingsFiatRoute
  '/settings/fio-plugin': typeof TerminalSettingsFioPluginRoute
  '/settings/items': typeof TerminalSettingsItemsRouteWithChildren
  '/settings/language': typeof TerminalSettingsLanguageRoute
  '/settings/payment-accounts': typeof TerminalSettingsPaymentAccountsRoute
  '/settings/payment-number-series': typeof TerminalSettingsPaymentNumberSeriesRoute
  '/settings/privacy': typeof TerminalSettingsPrivacyRoute
  '/settings/security': typeof TerminalSettingsSecurityRoute
  '/settings/tables': typeof TerminalSettingsTablesRouteWithChildren
  '/settings/theme': typeof TerminalSettingsThemeRoute
  '/settings/tips': typeof TerminalSettingsTipsRoute
  '/settings/withdraw': typeof TerminalSettingsWithdrawRoute
  '/settings/': typeof TerminalSettingsIndexRoute
  '/settings/about/privacy': typeof TerminalSettingsAboutPrivacyRoute
  '/settings/about/terms': typeof TerminalSettingsAboutTermsRoute
  '/settings/categories/$catalogCategoryId': typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  '/settings/categories/new': typeof TerminalSettingsCategoriesNewRoute
  '/settings/items/$catalogItemId': typeof TerminalSettingsItemsCatalogItemIdRoute
  '/settings/items/new': typeof TerminalSettingsItemsNewRoute
  '/settings/tables/$tableId': typeof TerminalSettingsTablesTableIdRoute
  '/settings/tables/new': typeof TerminalSettingsTablesNewRoute
  '/settings/about/': typeof TerminalSettingsAboutIndexRoute
  '/settings/categories/': typeof TerminalSettingsCategoriesIndexRoute
  '/settings/items/': typeof TerminalSettingsItemsIndexRoute
  '/settings/tables/': typeof TerminalSettingsTablesIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/restore-account': typeof RestoreAccountRoute
  '/activity': typeof TerminalActivityRoute
  '/bill': typeof TerminalBillRoute
  '/': typeof TerminalIndexRoute
  '/activity/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/payment/tip': typeof TerminalPaymentTipRoute
  '/payment/$paymentId': typeof TerminalPaymentPaymentIdRoute
  '/settings/accounts': typeof TerminalSettingsAccountsRoute
  '/settings/debug-console': typeof TerminalSettingsDebugConsoleRoute
  '/settings/default-payment-method': typeof TerminalSettingsDefaultPaymentMethodRoute
  '/settings/donations': typeof TerminalSettingsDonationsRoute
  '/settings/donations-invoice': typeof TerminalSettingsDonationsInvoiceRoute
  '/settings/evolu-export': typeof TerminalSettingsEvoluExportRoute
  '/settings/fiat': typeof TerminalSettingsFiatRoute
  '/settings/fio-plugin': typeof TerminalSettingsFioPluginRoute
  '/settings/language': typeof TerminalSettingsLanguageRoute
  '/settings/payment-accounts': typeof TerminalSettingsPaymentAccountsRoute
  '/settings/payment-number-series': typeof TerminalSettingsPaymentNumberSeriesRoute
  '/settings/privacy': typeof TerminalSettingsPrivacyRoute
  '/settings/security': typeof TerminalSettingsSecurityRoute
  '/settings/theme': typeof TerminalSettingsThemeRoute
  '/settings/tips': typeof TerminalSettingsTipsRoute
  '/settings/withdraw': typeof TerminalSettingsWithdrawRoute
  '/settings': typeof TerminalSettingsIndexRoute
  '/settings/about/privacy': typeof TerminalSettingsAboutPrivacyRoute
  '/settings/about/terms': typeof TerminalSettingsAboutTermsRoute
  '/settings/categories/$catalogCategoryId': typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  '/settings/categories/new': typeof TerminalSettingsCategoriesNewRoute
  '/settings/items/$catalogItemId': typeof TerminalSettingsItemsCatalogItemIdRoute
  '/settings/items/new': typeof TerminalSettingsItemsNewRoute
  '/settings/tables/$tableId': typeof TerminalSettingsTablesTableIdRoute
  '/settings/tables/new': typeof TerminalSettingsTablesNewRoute
  '/settings/about': typeof TerminalSettingsAboutIndexRoute
  '/settings/categories': typeof TerminalSettingsCategoriesIndexRoute
  '/settings/items': typeof TerminalSettingsItemsIndexRoute
  '/settings/tables': typeof TerminalSettingsTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_terminal': typeof TerminalRouteWithChildren
  '/error': typeof ErrorRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/restore-account': typeof RestoreAccountRoute
  '/_terminal/activity': typeof TerminalActivityRoute
  '/_terminal/bill': typeof TerminalBillRoute
  '/_terminal/settings': typeof TerminalSettingsRouteWithChildren
  '/_terminal/': typeof TerminalIndexRoute
  '/_terminal/activity_/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/_terminal/payment/tip': typeof TerminalPaymentTipRoute
  '/_terminal/payment_/$paymentId': typeof TerminalPaymentPaymentIdRoute
  '/_terminal/settings/about': typeof TerminalSettingsAboutRouteWithChildren
  '/_terminal/settings/accounts': typeof TerminalSettingsAccountsRoute
  '/_terminal/settings/categories': typeof TerminalSettingsCategoriesRouteWithChildren
  '/_terminal/settings/debug-console': typeof TerminalSettingsDebugConsoleRoute
  '/_terminal/settings/default-payment-method': typeof TerminalSettingsDefaultPaymentMethodRoute
  '/_terminal/settings/donations': typeof TerminalSettingsDonationsRoute
  '/_terminal/settings/donations-invoice': typeof TerminalSettingsDonationsInvoiceRoute
  '/_terminal/settings/evolu-export': typeof TerminalSettingsEvoluExportRoute
  '/_terminal/settings/fiat': typeof TerminalSettingsFiatRoute
  '/_terminal/settings/fio-plugin': typeof TerminalSettingsFioPluginRoute
  '/_terminal/settings/items': typeof TerminalSettingsItemsRouteWithChildren
  '/_terminal/settings/language': typeof TerminalSettingsLanguageRoute
  '/_terminal/settings/payment-accounts': typeof TerminalSettingsPaymentAccountsRoute
  '/_terminal/settings/payment-number-series': typeof TerminalSettingsPaymentNumberSeriesRoute
  '/_terminal/settings/privacy': typeof TerminalSettingsPrivacyRoute
  '/_terminal/settings/security': typeof TerminalSettingsSecurityRoute
  '/_terminal/settings/tables': typeof TerminalSettingsTablesRouteWithChildren
  '/_terminal/settings/theme': typeof TerminalSettingsThemeRoute
  '/_terminal/settings/tips': typeof TerminalSettingsTipsRoute
  '/_terminal/settings/withdraw': typeof TerminalSettingsWithdrawRoute
  '/_terminal/settings/': typeof TerminalSettingsIndexRoute
  '/_terminal/settings/about/privacy': typeof TerminalSettingsAboutPrivacyRoute
  '/_terminal/settings/about/terms': typeof TerminalSettingsAboutTermsRoute
  '/_terminal/settings/categories/$catalogCategoryId': typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  '/_terminal/settings/categories/new': typeof TerminalSettingsCategoriesNewRoute
  '/_terminal/settings/items/$catalogItemId': typeof TerminalSettingsItemsCatalogItemIdRoute
  '/_terminal/settings/items/new': typeof TerminalSettingsItemsNewRoute
  '/_terminal/settings/tables/$tableId': typeof TerminalSettingsTablesTableIdRoute
  '/_terminal/settings/tables/new': typeof TerminalSettingsTablesNewRoute
  '/_terminal/settings/about/': typeof TerminalSettingsAboutIndexRoute
  '/_terminal/settings/categories/': typeof TerminalSettingsCategoriesIndexRoute
  '/_terminal/settings/items/': typeof TerminalSettingsItemsIndexRoute
  '/_terminal/settings/tables/': typeof TerminalSettingsTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/landing'
    | '/onboarding'
    | '/restore-account'
    | '/activity'
    | '/bill'
    | '/settings'
    | '/activity/$paymentId'
    | '/payment/tip'
    | '/payment/$paymentId'
    | '/settings/about'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/debug-console'
    | '/settings/default-payment-method'
    | '/settings/donations'
    | '/settings/donations-invoice'
    | '/settings/evolu-export'
    | '/settings/fiat'
    | '/settings/fio-plugin'
    | '/settings/items'
    | '/settings/language'
    | '/settings/payment-accounts'
    | '/settings/payment-number-series'
    | '/settings/privacy'
    | '/settings/security'
    | '/settings/tables'
    | '/settings/theme'
    | '/settings/tips'
    | '/settings/withdraw'
    | '/settings/'
    | '/settings/about/privacy'
    | '/settings/about/terms'
    | '/settings/categories/$catalogCategoryId'
    | '/settings/categories/new'
    | '/settings/items/$catalogItemId'
    | '/settings/items/new'
    | '/settings/tables/$tableId'
    | '/settings/tables/new'
    | '/settings/about/'
    | '/settings/categories/'
    | '/settings/items/'
    | '/settings/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/landing'
    | '/onboarding'
    | '/restore-account'
    | '/activity'
    | '/bill'
    | '/'
    | '/activity/$paymentId'
    | '/payment/tip'
    | '/payment/$paymentId'
    | '/settings/accounts'
    | '/settings/debug-console'
    | '/settings/default-payment-method'
    | '/settings/donations'
    | '/settings/donations-invoice'
    | '/settings/evolu-export'
    | '/settings/fiat'
    | '/settings/fio-plugin'
    | '/settings/language'
    | '/settings/payment-accounts'
    | '/settings/payment-number-series'
    | '/settings/privacy'
    | '/settings/security'
    | '/settings/theme'
    | '/settings/tips'
    | '/settings/withdraw'
    | '/settings'
    | '/settings/about/privacy'
    | '/settings/about/terms'
    | '/settings/categories/$catalogCategoryId'
    | '/settings/categories/new'
    | '/settings/items/$catalogItemId'
    | '/settings/items/new'
    | '/settings/tables/$tableId'
    | '/settings/tables/new'
    | '/settings/about'
    | '/settings/categories'
    | '/settings/items'
    | '/settings/tables'
  id:
    | '__root__'
    | '/_terminal'
    | '/error'
    | '/landing'
    | '/onboarding'
    | '/restore-account'
    | '/_terminal/activity'
    | '/_terminal/bill'
    | '/_terminal/settings'
    | '/_terminal/'
    | '/_terminal/activity_/$paymentId'
    | '/_terminal/payment/tip'
    | '/_terminal/payment_/$paymentId'
    | '/_terminal/settings/about'
    | '/_terminal/settings/accounts'
    | '/_terminal/settings/categories'
    | '/_terminal/settings/debug-console'
    | '/_terminal/settings/default-payment-method'
    | '/_terminal/settings/donations'
    | '/_terminal/settings/donations-invoice'
    | '/_terminal/settings/evolu-export'
    | '/_terminal/settings/fiat'
    | '/_terminal/settings/fio-plugin'
    | '/_terminal/settings/items'
    | '/_terminal/settings/language'
    | '/_terminal/settings/payment-accounts'
    | '/_terminal/settings/payment-number-series'
    | '/_terminal/settings/privacy'
    | '/_terminal/settings/security'
    | '/_terminal/settings/tables'
    | '/_terminal/settings/theme'
    | '/_terminal/settings/tips'
    | '/_terminal/settings/withdraw'
    | '/_terminal/settings/'
    | '/_terminal/settings/about/privacy'
    | '/_terminal/settings/about/terms'
    | '/_terminal/settings/categories/$catalogCategoryId'
    | '/_terminal/settings/categories/new'
    | '/_terminal/settings/items/$catalogItemId'
    | '/_terminal/settings/items/new'
    | '/_terminal/settings/tables/$tableId'
    | '/_terminal/settings/tables/new'
    | '/_terminal/settings/about/'
    | '/_terminal/settings/categories/'
    | '/_terminal/settings/items/'
    | '/_terminal/settings/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TerminalRoute: typeof TerminalRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LandingRoute: typeof LandingRoute
  OnboardingRoute: typeof OnboardingRoute
  RestoreAccountRoute: typeof RestoreAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_terminal': {
      id: '/_terminal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore-account': {
      id: '/restore-account'
      path: '/restore-account'
      fullPath: '/restore-account'
      preLoaderRoute: typeof RestoreAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal/': {
      id: '/_terminal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity': {
      id: '/_terminal/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof TerminalActivityRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/bill': {
      id: '/_terminal/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof TerminalBillRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings': {
      id: '/_terminal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TerminalSettingsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity_/$paymentId': {
      id: '/_terminal/activity_/$paymentId'
      path: '/activity/$paymentId'
      fullPath: '/activity/$paymentId'
      preLoaderRoute: typeof TerminalActivityPaymentIdRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/payment/tip': {
      id: '/_terminal/payment/tip'
      path: '/payment/tip'
      fullPath: '/payment/tip'
      preLoaderRoute: typeof TerminalPaymentTipRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/payment_/$paymentId': {
      id: '/_terminal/payment_/$paymentId'
      path: '/payment/$paymentId'
      fullPath: '/payment/$paymentId'
      preLoaderRoute: typeof TerminalPaymentPaymentIdRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings/': {
      id: '/_terminal/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof TerminalSettingsIndexRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/about': {
      id: '/_terminal/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof TerminalSettingsAboutRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/accounts': {
      id: '/_terminal/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof TerminalSettingsAccountsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/categories': {
      id: '/_terminal/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof TerminalSettingsCategoriesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/debug-console': {
      id: '/_terminal/settings/debug-console'
      path: '/debug-console'
      fullPath: '/settings/debug-console'
      preLoaderRoute: typeof TerminalSettingsDebugConsoleRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/default-payment-method': {
      id: '/_terminal/settings/default-payment-method'
      path: '/default-payment-method'
      fullPath: '/settings/default-payment-method'
      preLoaderRoute: typeof TerminalSettingsDefaultPaymentMethodRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/donations': {
      id: '/_terminal/settings/donations'
      path: '/donations'
      fullPath: '/settings/donations'
      preLoaderRoute: typeof TerminalSettingsDonationsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/donations-invoice': {
      id: '/_terminal/settings/donations-invoice'
      path: '/donations-invoice'
      fullPath: '/settings/donations-invoice'
      preLoaderRoute: typeof TerminalSettingsDonationsInvoiceRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/evolu-export': {
      id: '/_terminal/settings/evolu-export'
      path: '/evolu-export'
      fullPath: '/settings/evolu-export'
      preLoaderRoute: typeof TerminalSettingsEvoluExportRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/fiat': {
      id: '/_terminal/settings/fiat'
      path: '/fiat'
      fullPath: '/settings/fiat'
      preLoaderRoute: typeof TerminalSettingsFiatRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/fio-plugin': {
      id: '/_terminal/settings/fio-plugin'
      path: '/fio-plugin'
      fullPath: '/settings/fio-plugin'
      preLoaderRoute: typeof TerminalSettingsFioPluginRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/items': {
      id: '/_terminal/settings/items'
      path: '/items'
      fullPath: '/settings/items'
      preLoaderRoute: typeof TerminalSettingsItemsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/language': {
      id: '/_terminal/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof TerminalSettingsLanguageRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/payment-accounts': {
      id: '/_terminal/settings/payment-accounts'
      path: '/payment-accounts'
      fullPath: '/settings/payment-accounts'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/payment-number-series': {
      id: '/_terminal/settings/payment-number-series'
      path: '/payment-number-series'
      fullPath: '/settings/payment-number-series'
      preLoaderRoute: typeof TerminalSettingsPaymentNumberSeriesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/privacy': {
      id: '/_terminal/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof TerminalSettingsPrivacyRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/security': {
      id: '/_terminal/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof TerminalSettingsSecurityRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/tables': {
      id: '/_terminal/settings/tables'
      path: '/tables'
      fullPath: '/settings/tables'
      preLoaderRoute: typeof TerminalSettingsTablesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/theme': {
      id: '/_terminal/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof TerminalSettingsThemeRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/tips': {
      id: '/_terminal/settings/tips'
      path: '/tips'
      fullPath: '/settings/tips'
      preLoaderRoute: typeof TerminalSettingsTipsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/withdraw': {
      id: '/_terminal/settings/withdraw'
      path: '/withdraw'
      fullPath: '/settings/withdraw'
      preLoaderRoute: typeof TerminalSettingsWithdrawRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/about/': {
      id: '/_terminal/settings/about/'
      path: '/'
      fullPath: '/settings/about/'
      preLoaderRoute: typeof TerminalSettingsAboutIndexRouteImport
      parentRoute: typeof TerminalSettingsAboutRoute
    }
    '/_terminal/settings/about/privacy': {
      id: '/_terminal/settings/about/privacy'
      path: '/privacy'
      fullPath: '/settings/about/privacy'
      preLoaderRoute: typeof TerminalSettingsAboutPrivacyRouteImport
      parentRoute: typeof TerminalSettingsAboutRoute
    }
    '/_terminal/settings/about/terms': {
      id: '/_terminal/settings/about/terms'
      path: '/terms'
      fullPath: '/settings/about/terms'
      preLoaderRoute: typeof TerminalSettingsAboutTermsRouteImport
      parentRoute: typeof TerminalSettingsAboutRoute
    }
    '/_terminal/settings/categories/': {
      id: '/_terminal/settings/categories/'
      path: '/'
      fullPath: '/settings/categories/'
      preLoaderRoute: typeof TerminalSettingsCategoriesIndexRouteImport
      parentRoute: typeof TerminalSettingsCategoriesRoute
    }
    '/_terminal/settings/categories/$catalogCategoryId': {
      id: '/_terminal/settings/categories/$catalogCategoryId'
      path: '/$catalogCategoryId'
      fullPath: '/settings/categories/$catalogCategoryId'
      preLoaderRoute: typeof TerminalSettingsCategoriesCatalogCategoryIdRouteImport
      parentRoute: typeof TerminalSettingsCategoriesRoute
    }
    '/_terminal/settings/categories/new': {
      id: '/_terminal/settings/categories/new'
      path: '/new'
      fullPath: '/settings/categories/new'
      preLoaderRoute: typeof TerminalSettingsCategoriesNewRouteImport
      parentRoute: typeof TerminalSettingsCategoriesRoute
    }
    '/_terminal/settings/items/': {
      id: '/_terminal/settings/items/'
      path: '/'
      fullPath: '/settings/items/'
      preLoaderRoute: typeof TerminalSettingsItemsIndexRouteImport
      parentRoute: typeof TerminalSettingsItemsRoute
    }
    '/_terminal/settings/items/$catalogItemId': {
      id: '/_terminal/settings/items/$catalogItemId'
      path: '/$catalogItemId'
      fullPath: '/settings/items/$catalogItemId'
      preLoaderRoute: typeof TerminalSettingsItemsCatalogItemIdRouteImport
      parentRoute: typeof TerminalSettingsItemsRoute
    }
    '/_terminal/settings/items/new': {
      id: '/_terminal/settings/items/new'
      path: '/new'
      fullPath: '/settings/items/new'
      preLoaderRoute: typeof TerminalSettingsItemsNewRouteImport
      parentRoute: typeof TerminalSettingsItemsRoute
    }
    '/_terminal/settings/tables/': {
      id: '/_terminal/settings/tables/'
      path: '/'
      fullPath: '/settings/tables/'
      preLoaderRoute: typeof TerminalSettingsTablesIndexRouteImport
      parentRoute: typeof TerminalSettingsTablesRoute
    }
    '/_terminal/settings/tables/$tableId': {
      id: '/_terminal/settings/tables/$tableId'
      path: '/$tableId'
      fullPath: '/settings/tables/$tableId'
      preLoaderRoute: typeof TerminalSettingsTablesTableIdRouteImport
      parentRoute: typeof TerminalSettingsTablesRoute
    }
    '/_terminal/settings/tables/new': {
      id: '/_terminal/settings/tables/new'
      path: '/new'
      fullPath: '/settings/tables/new'
      preLoaderRoute: typeof TerminalSettingsTablesNewRouteImport
      parentRoute: typeof TerminalSettingsTablesRoute
    }
  }
}

interface TerminalSettingsAboutRouteChildren {
  TerminalSettingsAboutPrivacyRoute: typeof TerminalSettingsAboutPrivacyRoute
  TerminalSettingsAboutTermsRoute: typeof TerminalSettingsAboutTermsRoute
  TerminalSettingsAboutIndexRoute: typeof TerminalSettingsAboutIndexRoute
}

const TerminalSettingsAboutRouteChildren: TerminalSettingsAboutRouteChildren = {
  TerminalSettingsAboutPrivacyRoute: TerminalSettingsAboutPrivacyRoute,
  TerminalSettingsAboutTermsRoute: TerminalSettingsAboutTermsRoute,
  TerminalSettingsAboutIndexRoute: TerminalSettingsAboutIndexRoute,
}

const TerminalSettingsAboutRouteWithChildren =
  TerminalSettingsAboutRoute._addFileChildren(
    TerminalSettingsAboutRouteChildren,
  )

interface TerminalSettingsCategoriesRouteChildren {
  TerminalSettingsCategoriesCatalogCategoryIdRoute: typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  TerminalSettingsCategoriesNewRoute: typeof TerminalSettingsCategoriesNewRoute
  TerminalSettingsCategoriesIndexRoute: typeof TerminalSettingsCategoriesIndexRoute
}

const TerminalSettingsCategoriesRouteChildren: TerminalSettingsCategoriesRouteChildren =
  {
    TerminalSettingsCategoriesCatalogCategoryIdRoute:
      TerminalSettingsCategoriesCatalogCategoryIdRoute,
    TerminalSettingsCategoriesNewRoute: TerminalSettingsCategoriesNewRoute,
    TerminalSettingsCategoriesIndexRoute: TerminalSettingsCategoriesIndexRoute,
  }

const TerminalSettingsCategoriesRouteWithChildren =
  TerminalSettingsCategoriesRoute._addFileChildren(
    TerminalSettingsCategoriesRouteChildren,
  )

interface TerminalSettingsItemsRouteChildren {
  TerminalSettingsItemsCatalogItemIdRoute: typeof TerminalSettingsItemsCatalogItemIdRoute
  TerminalSettingsItemsNewRoute: typeof TerminalSettingsItemsNewRoute
  TerminalSettingsItemsIndexRoute: typeof TerminalSettingsItemsIndexRoute
}

const TerminalSettingsItemsRouteChildren: TerminalSettingsItemsRouteChildren = {
  TerminalSettingsItemsCatalogItemIdRoute:
    TerminalSettingsItemsCatalogItemIdRoute,
  TerminalSettingsItemsNewRoute: TerminalSettingsItemsNewRoute,
  TerminalSettingsItemsIndexRoute: TerminalSettingsItemsIndexRoute,
}

const TerminalSettingsItemsRouteWithChildren =
  TerminalSettingsItemsRoute._addFileChildren(
    TerminalSettingsItemsRouteChildren,
  )

interface TerminalSettingsTablesRouteChildren {
  TerminalSettingsTablesTableIdRoute: typeof TerminalSettingsTablesTableIdRoute
  TerminalSettingsTablesNewRoute: typeof TerminalSettingsTablesNewRoute
  TerminalSettingsTablesIndexRoute: typeof TerminalSettingsTablesIndexRoute
}

const TerminalSettingsTablesRouteChildren: TerminalSettingsTablesRouteChildren =
  {
    TerminalSettingsTablesTableIdRoute: TerminalSettingsTablesTableIdRoute,
    TerminalSettingsTablesNewRoute: TerminalSettingsTablesNewRoute,
    TerminalSettingsTablesIndexRoute: TerminalSettingsTablesIndexRoute,
  }

const TerminalSettingsTablesRouteWithChildren =
  TerminalSettingsTablesRoute._addFileChildren(
    TerminalSettingsTablesRouteChildren,
  )

interface TerminalSettingsRouteChildren {
  TerminalSettingsAboutRoute: typeof TerminalSettingsAboutRouteWithChildren
  TerminalSettingsAccountsRoute: typeof TerminalSettingsAccountsRoute
  TerminalSettingsCategoriesRoute: typeof TerminalSettingsCategoriesRouteWithChildren
  TerminalSettingsDebugConsoleRoute: typeof TerminalSettingsDebugConsoleRoute
  TerminalSettingsDefaultPaymentMethodRoute: typeof TerminalSettingsDefaultPaymentMethodRoute
  TerminalSettingsDonationsRoute: typeof TerminalSettingsDonationsRoute
  TerminalSettingsDonationsInvoiceRoute: typeof TerminalSettingsDonationsInvoiceRoute
  TerminalSettingsEvoluExportRoute: typeof TerminalSettingsEvoluExportRoute
  TerminalSettingsFiatRoute: typeof TerminalSettingsFiatRoute
  TerminalSettingsFioPluginRoute: typeof TerminalSettingsFioPluginRoute
  TerminalSettingsItemsRoute: typeof TerminalSettingsItemsRouteWithChildren
  TerminalSettingsLanguageRoute: typeof TerminalSettingsLanguageRoute
  TerminalSettingsPaymentAccountsRoute: typeof TerminalSettingsPaymentAccountsRoute
  TerminalSettingsPaymentNumberSeriesRoute: typeof TerminalSettingsPaymentNumberSeriesRoute
  TerminalSettingsPrivacyRoute: typeof TerminalSettingsPrivacyRoute
  TerminalSettingsSecurityRoute: typeof TerminalSettingsSecurityRoute
  TerminalSettingsTablesRoute: typeof TerminalSettingsTablesRouteWithChildren
  TerminalSettingsThemeRoute: typeof TerminalSettingsThemeRoute
  TerminalSettingsTipsRoute: typeof TerminalSettingsTipsRoute
  TerminalSettingsWithdrawRoute: typeof TerminalSettingsWithdrawRoute
  TerminalSettingsIndexRoute: typeof TerminalSettingsIndexRoute
}

const TerminalSettingsRouteChildren: TerminalSettingsRouteChildren = {
  TerminalSettingsAboutRoute: TerminalSettingsAboutRouteWithChildren,
  TerminalSettingsAccountsRoute: TerminalSettingsAccountsRoute,
  TerminalSettingsCategoriesRoute: TerminalSettingsCategoriesRouteWithChildren,
  TerminalSettingsDebugConsoleRoute: TerminalSettingsDebugConsoleRoute,
  TerminalSettingsDefaultPaymentMethodRoute:
    TerminalSettingsDefaultPaymentMethodRoute,
  TerminalSettingsDonationsRoute: TerminalSettingsDonationsRoute,
  TerminalSettingsDonationsInvoiceRoute: TerminalSettingsDonationsInvoiceRoute,
  TerminalSettingsEvoluExportRoute: TerminalSettingsEvoluExportRoute,
  TerminalSettingsFiatRoute: TerminalSettingsFiatRoute,
  TerminalSettingsFioPluginRoute: TerminalSettingsFioPluginRoute,
  TerminalSettingsItemsRoute: TerminalSettingsItemsRouteWithChildren,
  TerminalSettingsLanguageRoute: TerminalSettingsLanguageRoute,
  TerminalSettingsPaymentAccountsRoute: TerminalSettingsPaymentAccountsRoute,
  TerminalSettingsPaymentNumberSeriesRoute:
    TerminalSettingsPaymentNumberSeriesRoute,
  TerminalSettingsPrivacyRoute: TerminalSettingsPrivacyRoute,
  TerminalSettingsSecurityRoute: TerminalSettingsSecurityRoute,
  TerminalSettingsTablesRoute: TerminalSettingsTablesRouteWithChildren,
  TerminalSettingsThemeRoute: TerminalSettingsThemeRoute,
  TerminalSettingsTipsRoute: TerminalSettingsTipsRoute,
  TerminalSettingsWithdrawRoute: TerminalSettingsWithdrawRoute,
  TerminalSettingsIndexRoute: TerminalSettingsIndexRoute,
}

const TerminalSettingsRouteWithChildren =
  TerminalSettingsRoute._addFileChildren(TerminalSettingsRouteChildren)

interface TerminalRouteChildren {
  TerminalActivityRoute: typeof TerminalActivityRoute
  TerminalBillRoute: typeof TerminalBillRoute
  TerminalSettingsRoute: typeof TerminalSettingsRouteWithChildren
  TerminalIndexRoute: typeof TerminalIndexRoute
  TerminalActivityPaymentIdRoute: typeof TerminalActivityPaymentIdRoute
  TerminalPaymentTipRoute: typeof TerminalPaymentTipRoute
  TerminalPaymentPaymentIdRoute: typeof TerminalPaymentPaymentIdRoute
}

const TerminalRouteChildren: TerminalRouteChildren = {
  TerminalActivityRoute: TerminalActivityRoute,
  TerminalBillRoute: TerminalBillRoute,
  TerminalSettingsRoute: TerminalSettingsRouteWithChildren,
  TerminalIndexRoute: TerminalIndexRoute,
  TerminalActivityPaymentIdRoute: TerminalActivityPaymentIdRoute,
  TerminalPaymentTipRoute: TerminalPaymentTipRoute,
  TerminalPaymentPaymentIdRoute: TerminalPaymentPaymentIdRoute,
}

const TerminalRouteWithChildren = TerminalRoute._addFileChildren(
  TerminalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TerminalRoute: TerminalRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LandingRoute: LandingRoute,
  OnboardingRoute: OnboardingRoute,
  RestoreAccountRoute: RestoreAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
