/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/_terminal'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RestoreAccountRouteImport } from './routes/restore-account'
import { Route as TerminalIndexRouteImport } from './routes/_terminal.index'
import { Route as TerminalActivityRouteImport } from './routes/_terminal.activity'
import { Route as TerminalBillRouteImport } from './routes/_terminal.bill'
import { Route as TerminalSettingsRouteImport } from './routes/_terminal.settings'
import { Route as TerminalActivityPaymentIdRouteImport } from './routes/_terminal.activity_.$paymentId'
import { Route as TerminalActivityBillsRouteImport } from './routes/_terminal.activity_.bills'
import { Route as TerminalPaymentTipRouteImport } from './routes/_terminal.payment.tip'
import { Route as TerminalPaymentPaymentIdRouteImport } from './routes/_terminal.payment_.$paymentId'
import { Route as TerminalSettingsIndexRouteImport } from './routes/_terminal.settings.index'
import { Route as TerminalSettingsAboutRouteImport } from './routes/_terminal.settings.about'
import { Route as TerminalSettingsAccessRouteImport } from './routes/_terminal.settings.access'
import { Route as TerminalSettingsAccountsRouteImport } from './routes/_terminal.settings.accounts'
import { Route as TerminalSettingsAssistantRouteImport } from './routes/_terminal.settings.assistant'
import { Route as TerminalSettingsCategoriesRouteImport } from './routes/_terminal.settings.categories'
import { Route as TerminalSettingsDebugConsoleRouteImport } from './routes/_terminal.settings.debug-console'
import { Route as TerminalSettingsDonationsRouteImport } from './routes/_terminal.settings.donations'
import { Route as TerminalSettingsDonationsInvoiceRouteImport } from './routes/_terminal.settings.donations-invoice'
import { Route as TerminalSettingsEetRouteImport } from './routes/_terminal.settings.eet'
import { Route as TerminalSettingsEvoluExportRouteImport } from './routes/_terminal.settings.evolu-export'
import { Route as TerminalSettingsHomeScreenRouteImport } from './routes/_terminal.settings.home-screen'
import { Route as TerminalSettingsItemsRouteImport } from './routes/_terminal.settings.items'
import { Route as TerminalSettingsLanguageRouteImport } from './routes/_terminal.settings.language'
import { Route as TerminalSettingsLegalEntityRouteImport } from './routes/_terminal.settings.legal-entity'
import { Route as TerminalSettingsPaymentAccountsRouteImport } from './routes/_terminal.settings.payment-accounts'
import { Route as TerminalSettingsPaymentNumberSeriesRouteImport } from './routes/_terminal.settings.payment-number-series'
import { Route as TerminalSettingsProfileRouteImport } from './routes/_terminal.settings.profile'
import { Route as TerminalSettingsSecurityRouteImport } from './routes/_terminal.settings.security'
import { Route as TerminalSettingsSupportRouteImport } from './routes/_terminal.settings.support'
import { Route as TerminalSettingsTablesRouteImport } from './routes/_terminal.settings.tables'
import { Route as TerminalSettingsTaxRatesRouteImport } from './routes/_terminal.settings.tax-rates'
import { Route as TerminalSettingsThemeRouteImport } from './routes/_terminal.settings.theme'
import { Route as TerminalSettingsTipsRouteImport } from './routes/_terminal.settings.tips'
import { Route as TerminalActivityBillsBillIdRouteImport } from './routes/_terminal.activity_.bills_.$billId'
import { Route as TerminalSettingsAboutIndexRouteImport } from './routes/_terminal.settings.about.index'
import { Route as TerminalSettingsAboutPrivacyRouteImport } from './routes/_terminal.settings.about.privacy'
import { Route as TerminalSettingsAboutTermsRouteImport } from './routes/_terminal.settings.about.terms'
import { Route as TerminalSettingsAccessAddDeviceRouteImport } from './routes/_terminal.settings.access_.add-device'
import { Route as TerminalSettingsAccountsIndexRouteImport } from './routes/_terminal.settings.accounts.index'
import { Route as TerminalSettingsCategoriesIndexRouteImport } from './routes/_terminal.settings.categories.index'
import { Route as TerminalSettingsCategoriesCatalogCategoryIdRouteImport } from './routes/_terminal.settings.categories.$catalogCategoryId'
import { Route as TerminalSettingsCategoriesNewRouteImport } from './routes/_terminal.settings.categories.new'
import { Route as TerminalSettingsItemsIndexRouteImport } from './routes/_terminal.settings.items.index'
import { Route as TerminalSettingsItemsCatalogItemIdRouteImport } from './routes/_terminal.settings.items.$catalogItemId'
import { Route as TerminalSettingsItemsNewRouteImport } from './routes/_terminal.settings.items.new'
import { Route as TerminalSettingsPaymentAccountsIndexRouteImport } from './routes/_terminal.settings.payment-accounts.index'
import { Route as TerminalSettingsPaymentAccountsCardSwitchioRouteImport } from './routes/_terminal.settings.payment-accounts.card-switchio'
import { Route as TerminalSettingsPaymentAccountsIbanRouteImport } from './routes/_terminal.settings.payment-accounts.iban'
import { Route as TerminalSettingsPaymentAccountsSparkRouteImport } from './routes/_terminal.settings.payment-accounts.spark'
import { Route as TerminalSettingsTablesIndexRouteImport } from './routes/_terminal.settings.tables.index'
import { Route as TerminalSettingsTablesTableIdRouteImport } from './routes/_terminal.settings.tables.$tableId'
import { Route as TerminalSettingsTablesNewRouteImport } from './routes/_terminal.settings.tables.new'
import { Route as TerminalSettingsPaymentAccountsIbanIndexRouteImport } from './routes/_terminal.settings.payment-accounts.iban.index'
import { Route as TerminalSettingsPaymentAccountsIbanFioPluginRouteImport } from './routes/_terminal.settings.payment-accounts.iban.fio-plugin'
import { Route as TerminalSettingsPaymentAccountsSparkIndexRouteImport } from './routes/_terminal.settings.payment-accounts.spark.index'
import { Route as TerminalSettingsPaymentAccountsSparkTransactionsRouteImport } from './routes/_terminal.settings.payment-accounts.spark.transactions'
import { Route as TerminalSettingsPaymentAccountsSparkWithdrawalsRouteImport } from './routes/_terminal.settings.payment-accounts.spark.withdrawals'
import { Route as TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRouteImport } from './routes/_terminal.settings.payment-accounts.spark.withdrawals.index'
import { Route as TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRouteImport } from './routes/_terminal.settings.payment-accounts.spark.withdrawals.$withdrawalId'
import { Route as TerminalSettingsPaymentAccountsSparkWithdrawalsNewRouteImport } from './routes/_terminal.settings.payment-accounts.spark.withdrawals.new'

const TerminalRoute = TerminalRouteImport.update({
  id: '/_terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreAccountRoute = RestoreAccountRouteImport.update({
  id: '/restore-account',
  path: '/restore-account',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalActivityRoute = TerminalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalBillRoute = TerminalBillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalSettingsRoute = TerminalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalActivityPaymentIdRoute =
  TerminalActivityPaymentIdRouteImport.update({
    id: '/activity_/$paymentId',
    path: '/activity/$paymentId',
    getParentRoute: () => TerminalRoute,
  } as any)
const TerminalActivityBillsRoute = TerminalActivityBillsRouteImport.update({
  id: '/activity_/bills',
  path: '/activity/bills',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalPaymentTipRoute = TerminalPaymentTipRouteImport.update({
  id: '/payment/tip',
  path: '/payment/tip',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalPaymentPaymentIdRoute =
  TerminalPaymentPaymentIdRouteImport.update({
    id: '/payment_/$paymentId',
    path: '/payment/$paymentId',
    getParentRoute: () => TerminalRoute,
  } as any)
const TerminalSettingsIndexRoute = TerminalSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsAboutRoute = TerminalSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsAccessRoute = TerminalSettingsAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsAccountsRoute =
  TerminalSettingsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsAssistantRoute =
  TerminalSettingsAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsCategoriesRoute =
  TerminalSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDebugConsoleRoute =
  TerminalSettingsDebugConsoleRouteImport.update({
    id: '/debug-console',
    path: '/debug-console',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDonationsRoute =
  TerminalSettingsDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsDonationsInvoiceRoute =
  TerminalSettingsDonationsInvoiceRouteImport.update({
    id: '/donations-invoice',
    path: '/donations-invoice',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsEetRoute = TerminalSettingsEetRouteImport.update({
  id: '/eet',
  path: '/eet',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsEvoluExportRoute =
  TerminalSettingsEvoluExportRouteImport.update({
    id: '/evolu-export',
    path: '/evolu-export',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsHomeScreenRoute =
  TerminalSettingsHomeScreenRouteImport.update({
    id: '/home-screen',
    path: '/home-screen',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsItemsRoute = TerminalSettingsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsLanguageRoute =
  TerminalSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsLegalEntityRoute =
  TerminalSettingsLegalEntityRouteImport.update({
    id: '/legal-entity',
    path: '/legal-entity',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsPaymentAccountsRoute =
  TerminalSettingsPaymentAccountsRouteImport.update({
    id: '/payment-accounts',
    path: '/payment-accounts',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsPaymentNumberSeriesRoute =
  TerminalSettingsPaymentNumberSeriesRouteImport.update({
    id: '/payment-number-series',
    path: '/payment-number-series',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsProfileRoute = TerminalSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsSecurityRoute =
  TerminalSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsSupportRoute = TerminalSettingsSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsTablesRoute = TerminalSettingsTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsTaxRatesRoute =
  TerminalSettingsTaxRatesRouteImport.update({
    id: '/tax-rates',
    path: '/tax-rates',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsThemeRoute = TerminalSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalSettingsTipsRoute = TerminalSettingsTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => TerminalSettingsRoute,
} as any)
const TerminalActivityBillsBillIdRoute =
  TerminalActivityBillsBillIdRouteImport.update({
    id: '/activity_/bills_/$billId',
    path: '/activity/bills/$billId',
    getParentRoute: () => TerminalRoute,
  } as any)
const TerminalSettingsAboutIndexRoute =
  TerminalSettingsAboutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsAboutRoute,
  } as any)
const TerminalSettingsAboutPrivacyRoute =
  TerminalSettingsAboutPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => TerminalSettingsAboutRoute,
  } as any)
const TerminalSettingsAboutTermsRoute =
  TerminalSettingsAboutTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => TerminalSettingsAboutRoute,
  } as any)
const TerminalSettingsAccessAddDeviceRoute =
  TerminalSettingsAccessAddDeviceRouteImport.update({
    id: '/access_/add-device',
    path: '/access/add-device',
    getParentRoute: () => TerminalSettingsRoute,
  } as any)
const TerminalSettingsAccountsIndexRoute =
  TerminalSettingsAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsAccountsRoute,
  } as any)
const TerminalSettingsCategoriesIndexRoute =
  TerminalSettingsCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsCategoriesRoute,
  } as any)
const TerminalSettingsCategoriesCatalogCategoryIdRoute =
  TerminalSettingsCategoriesCatalogCategoryIdRouteImport.update({
    id: '/$catalogCategoryId',
    path: '/$catalogCategoryId',
    getParentRoute: () => TerminalSettingsCategoriesRoute,
  } as any)
const TerminalSettingsCategoriesNewRoute =
  TerminalSettingsCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsCategoriesRoute,
  } as any)
const TerminalSettingsItemsIndexRoute =
  TerminalSettingsItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsItemsRoute,
  } as any)
const TerminalSettingsItemsCatalogItemIdRoute =
  TerminalSettingsItemsCatalogItemIdRouteImport.update({
    id: '/$catalogItemId',
    path: '/$catalogItemId',
    getParentRoute: () => TerminalSettingsItemsRoute,
  } as any)
const TerminalSettingsItemsNewRoute =
  TerminalSettingsItemsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsItemsRoute,
  } as any)
const TerminalSettingsPaymentAccountsIndexRoute =
  TerminalSettingsPaymentAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsPaymentAccountsRoute,
  } as any)
const TerminalSettingsPaymentAccountsCardSwitchioRoute =
  TerminalSettingsPaymentAccountsCardSwitchioRouteImport.update({
    id: '/card-switchio',
    path: '/card-switchio',
    getParentRoute: () => TerminalSettingsPaymentAccountsRoute,
  } as any)
const TerminalSettingsPaymentAccountsIbanRoute =
  TerminalSettingsPaymentAccountsIbanRouteImport.update({
    id: '/iban',
    path: '/iban',
    getParentRoute: () => TerminalSettingsPaymentAccountsRoute,
  } as any)
const TerminalSettingsPaymentAccountsSparkRoute =
  TerminalSettingsPaymentAccountsSparkRouteImport.update({
    id: '/spark',
    path: '/spark',
    getParentRoute: () => TerminalSettingsPaymentAccountsRoute,
  } as any)
const TerminalSettingsTablesIndexRoute =
  TerminalSettingsTablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsTablesRoute,
  } as any)
const TerminalSettingsTablesTableIdRoute =
  TerminalSettingsTablesTableIdRouteImport.update({
    id: '/$tableId',
    path: '/$tableId',
    getParentRoute: () => TerminalSettingsTablesRoute,
  } as any)
const TerminalSettingsTablesNewRoute =
  TerminalSettingsTablesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsTablesRoute,
  } as any)
const TerminalSettingsPaymentAccountsIbanIndexRoute =
  TerminalSettingsPaymentAccountsIbanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsPaymentAccountsIbanRoute,
  } as any)
const TerminalSettingsPaymentAccountsIbanFioPluginRoute =
  TerminalSettingsPaymentAccountsIbanFioPluginRouteImport.update({
    id: '/fio-plugin',
    path: '/fio-plugin',
    getParentRoute: () => TerminalSettingsPaymentAccountsIbanRoute,
  } as any)
const TerminalSettingsPaymentAccountsSparkIndexRoute =
  TerminalSettingsPaymentAccountsSparkIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsPaymentAccountsSparkRoute,
  } as any)
const TerminalSettingsPaymentAccountsSparkTransactionsRoute =
  TerminalSettingsPaymentAccountsSparkTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => TerminalSettingsPaymentAccountsSparkRoute,
  } as any)
const TerminalSettingsPaymentAccountsSparkWithdrawalsRoute =
  TerminalSettingsPaymentAccountsSparkWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => TerminalSettingsPaymentAccountsSparkRoute,
  } as any)
const TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute =
  TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TerminalSettingsPaymentAccountsSparkWithdrawalsRoute,
  } as any)
const TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute =
  TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRouteImport.update(
    {
      id: '/$withdrawalId',
      path: '/$withdrawalId',
      getParentRoute: () =>
        TerminalSettingsPaymentAccountsSparkWithdrawalsRoute,
    } as any,
  )
const TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute =
  TerminalSettingsPaymentAccountsSparkWithdrawalsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TerminalSettingsPaymentAccountsSparkWithdrawalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof TerminalIndexRoute
  '/error': typeof ErrorRoute
  '/onboarding': typeof OnboardingRoute
  '/restore-account': typeof RestoreAccountRoute
  '/activity': typeof TerminalActivityRoute
  '/bill': typeof TerminalBillRoute
  '/settings': typeof TerminalSettingsRouteWithChildren
  '/activity/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/activity/bills': typeof TerminalActivityBillsRoute
  '/payment/tip': typeof TerminalPaymentTipRoute
  '/payment/$paymentId': typeof TerminalPaymentPaymentIdRoute
  '/settings/about': typeof TerminalSettingsAboutRouteWithChildren
  '/settings/access': typeof TerminalSettingsAccessRoute
  '/settings/accounts': typeof TerminalSettingsAccountsRouteWithChildren
  '/settings/assistant': typeof TerminalSettingsAssistantRoute
  '/settings/categories': typeof TerminalSettingsCategoriesRouteWithChildren
  '/settings/debug-console': typeof TerminalSettingsDebugConsoleRoute
  '/settings/donations': typeof TerminalSettingsDonationsRoute
  '/settings/donations-invoice': typeof TerminalSettingsDonationsInvoiceRoute
  '/settings/eet': typeof TerminalSettingsEetRoute
  '/settings/evolu-export': typeof TerminalSettingsEvoluExportRoute
  '/settings/home-screen': typeof TerminalSettingsHomeScreenRoute
  '/settings/items': typeof TerminalSettingsItemsRouteWithChildren
  '/settings/language': typeof TerminalSettingsLanguageRoute
  '/settings/legal-entity': typeof TerminalSettingsLegalEntityRoute
  '/settings/payment-accounts': typeof TerminalSettingsPaymentAccountsRouteWithChildren
  '/settings/payment-number-series': typeof TerminalSettingsPaymentNumberSeriesRoute
  '/settings/profile': typeof TerminalSettingsProfileRoute
  '/settings/security': typeof TerminalSettingsSecurityRoute
  '/settings/support': typeof TerminalSettingsSupportRoute
  '/settings/tables': typeof TerminalSettingsTablesRouteWithChildren
  '/settings/tax-rates': typeof TerminalSettingsTaxRatesRoute
  '/settings/theme': typeof TerminalSettingsThemeRoute
  '/settings/tips': typeof TerminalSettingsTipsRoute
  '/settings/': typeof TerminalSettingsIndexRoute
  '/activity/bills/$billId': typeof TerminalActivityBillsBillIdRoute
  '/settings/about/privacy': typeof TerminalSettingsAboutPrivacyRoute
  '/settings/about/terms': typeof TerminalSettingsAboutTermsRoute
  '/settings/access/add-device': typeof TerminalSettingsAccessAddDeviceRoute
  '/settings/categories/$catalogCategoryId': typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  '/settings/categories/new': typeof TerminalSettingsCategoriesNewRoute
  '/settings/items/$catalogItemId': typeof TerminalSettingsItemsCatalogItemIdRoute
  '/settings/items/new': typeof TerminalSettingsItemsNewRoute
  '/settings/payment-accounts/card-switchio': typeof TerminalSettingsPaymentAccountsCardSwitchioRoute
  '/settings/payment-accounts/iban': typeof TerminalSettingsPaymentAccountsIbanRouteWithChildren
  '/settings/payment-accounts/spark': typeof TerminalSettingsPaymentAccountsSparkRouteWithChildren
  '/settings/tables/$tableId': typeof TerminalSettingsTablesTableIdRoute
  '/settings/tables/new': typeof TerminalSettingsTablesNewRoute
  '/settings/about/': typeof TerminalSettingsAboutIndexRoute
  '/settings/accounts/': typeof TerminalSettingsAccountsIndexRoute
  '/settings/categories/': typeof TerminalSettingsCategoriesIndexRoute
  '/settings/items/': typeof TerminalSettingsItemsIndexRoute
  '/settings/payment-accounts/': typeof TerminalSettingsPaymentAccountsIndexRoute
  '/settings/tables/': typeof TerminalSettingsTablesIndexRoute
  '/settings/payment-accounts/iban/fio-plugin': typeof TerminalSettingsPaymentAccountsIbanFioPluginRoute
  '/settings/payment-accounts/spark/transactions': typeof TerminalSettingsPaymentAccountsSparkTransactionsRoute
  '/settings/payment-accounts/spark/withdrawals': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRouteWithChildren
  '/settings/payment-accounts/iban/': typeof TerminalSettingsPaymentAccountsIbanIndexRoute
  '/settings/payment-accounts/spark/': typeof TerminalSettingsPaymentAccountsSparkIndexRoute
  '/settings/payment-accounts/spark/withdrawals/$withdrawalId': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute
  '/settings/payment-accounts/spark/withdrawals/new': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute
  '/settings/payment-accounts/spark/withdrawals/': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/onboarding': typeof OnboardingRoute
  '/restore-account': typeof RestoreAccountRoute
  '/activity': typeof TerminalActivityRoute
  '/bill': typeof TerminalBillRoute
  '/': typeof TerminalIndexRoute
  '/activity/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/activity/bills': typeof TerminalActivityBillsRoute
  '/payment/tip': typeof TerminalPaymentTipRoute
  '/payment/$paymentId': typeof TerminalPaymentPaymentIdRoute
  '/settings/access': typeof TerminalSettingsAccessRoute
  '/settings/assistant': typeof TerminalSettingsAssistantRoute
  '/settings/debug-console': typeof TerminalSettingsDebugConsoleRoute
  '/settings/donations': typeof TerminalSettingsDonationsRoute
  '/settings/donations-invoice': typeof TerminalSettingsDonationsInvoiceRoute
  '/settings/eet': typeof TerminalSettingsEetRoute
  '/settings/evolu-export': typeof TerminalSettingsEvoluExportRoute
  '/settings/home-screen': typeof TerminalSettingsHomeScreenRoute
  '/settings/language': typeof TerminalSettingsLanguageRoute
  '/settings/legal-entity': typeof TerminalSettingsLegalEntityRoute
  '/settings/payment-number-series': typeof TerminalSettingsPaymentNumberSeriesRoute
  '/settings/profile': typeof TerminalSettingsProfileRoute
  '/settings/security': typeof TerminalSettingsSecurityRoute
  '/settings/support': typeof TerminalSettingsSupportRoute
  '/settings/tax-rates': typeof TerminalSettingsTaxRatesRoute
  '/settings/theme': typeof TerminalSettingsThemeRoute
  '/settings/tips': typeof TerminalSettingsTipsRoute
  '/settings': typeof TerminalSettingsIndexRoute
  '/activity/bills/$billId': typeof TerminalActivityBillsBillIdRoute
  '/settings/about/privacy': typeof TerminalSettingsAboutPrivacyRoute
  '/settings/about/terms': typeof TerminalSettingsAboutTermsRoute
  '/settings/access/add-device': typeof TerminalSettingsAccessAddDeviceRoute
  '/settings/categories/$catalogCategoryId': typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  '/settings/categories/new': typeof TerminalSettingsCategoriesNewRoute
  '/settings/items/$catalogItemId': typeof TerminalSettingsItemsCatalogItemIdRoute
  '/settings/items/new': typeof TerminalSettingsItemsNewRoute
  '/settings/payment-accounts/card-switchio': typeof TerminalSettingsPaymentAccountsCardSwitchioRoute
  '/settings/tables/$tableId': typeof TerminalSettingsTablesTableIdRoute
  '/settings/tables/new': typeof TerminalSettingsTablesNewRoute
  '/settings/about': typeof TerminalSettingsAboutIndexRoute
  '/settings/accounts': typeof TerminalSettingsAccountsIndexRoute
  '/settings/categories': typeof TerminalSettingsCategoriesIndexRoute
  '/settings/items': typeof TerminalSettingsItemsIndexRoute
  '/settings/payment-accounts': typeof TerminalSettingsPaymentAccountsIndexRoute
  '/settings/tables': typeof TerminalSettingsTablesIndexRoute
  '/settings/payment-accounts/iban/fio-plugin': typeof TerminalSettingsPaymentAccountsIbanFioPluginRoute
  '/settings/payment-accounts/spark/transactions': typeof TerminalSettingsPaymentAccountsSparkTransactionsRoute
  '/settings/payment-accounts/iban': typeof TerminalSettingsPaymentAccountsIbanIndexRoute
  '/settings/payment-accounts/spark': typeof TerminalSettingsPaymentAccountsSparkIndexRoute
  '/settings/payment-accounts/spark/withdrawals/$withdrawalId': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute
  '/settings/payment-accounts/spark/withdrawals/new': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute
  '/settings/payment-accounts/spark/withdrawals': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_terminal': typeof TerminalRouteWithChildren
  '/error': typeof ErrorRoute
  '/onboarding': typeof OnboardingRoute
  '/restore-account': typeof RestoreAccountRoute
  '/_terminal/activity': typeof TerminalActivityRoute
  '/_terminal/bill': typeof TerminalBillRoute
  '/_terminal/settings': typeof TerminalSettingsRouteWithChildren
  '/_terminal/': typeof TerminalIndexRoute
  '/_terminal/activity_/$paymentId': typeof TerminalActivityPaymentIdRoute
  '/_terminal/activity_/bills': typeof TerminalActivityBillsRoute
  '/_terminal/payment/tip': typeof TerminalPaymentTipRoute
  '/_terminal/payment_/$paymentId': typeof TerminalPaymentPaymentIdRoute
  '/_terminal/settings/about': typeof TerminalSettingsAboutRouteWithChildren
  '/_terminal/settings/access': typeof TerminalSettingsAccessRoute
  '/_terminal/settings/accounts': typeof TerminalSettingsAccountsRouteWithChildren
  '/_terminal/settings/assistant': typeof TerminalSettingsAssistantRoute
  '/_terminal/settings/categories': typeof TerminalSettingsCategoriesRouteWithChildren
  '/_terminal/settings/debug-console': typeof TerminalSettingsDebugConsoleRoute
  '/_terminal/settings/donations': typeof TerminalSettingsDonationsRoute
  '/_terminal/settings/donations-invoice': typeof TerminalSettingsDonationsInvoiceRoute
  '/_terminal/settings/eet': typeof TerminalSettingsEetRoute
  '/_terminal/settings/evolu-export': typeof TerminalSettingsEvoluExportRoute
  '/_terminal/settings/home-screen': typeof TerminalSettingsHomeScreenRoute
  '/_terminal/settings/items': typeof TerminalSettingsItemsRouteWithChildren
  '/_terminal/settings/language': typeof TerminalSettingsLanguageRoute
  '/_terminal/settings/legal-entity': typeof TerminalSettingsLegalEntityRoute
  '/_terminal/settings/payment-accounts': typeof TerminalSettingsPaymentAccountsRouteWithChildren
  '/_terminal/settings/payment-number-series': typeof TerminalSettingsPaymentNumberSeriesRoute
  '/_terminal/settings/profile': typeof TerminalSettingsProfileRoute
  '/_terminal/settings/security': typeof TerminalSettingsSecurityRoute
  '/_terminal/settings/support': typeof TerminalSettingsSupportRoute
  '/_terminal/settings/tables': typeof TerminalSettingsTablesRouteWithChildren
  '/_terminal/settings/tax-rates': typeof TerminalSettingsTaxRatesRoute
  '/_terminal/settings/theme': typeof TerminalSettingsThemeRoute
  '/_terminal/settings/tips': typeof TerminalSettingsTipsRoute
  '/_terminal/settings/': typeof TerminalSettingsIndexRoute
  '/_terminal/activity_/bills_/$billId': typeof TerminalActivityBillsBillIdRoute
  '/_terminal/settings/about/privacy': typeof TerminalSettingsAboutPrivacyRoute
  '/_terminal/settings/about/terms': typeof TerminalSettingsAboutTermsRoute
  '/_terminal/settings/access_/add-device': typeof TerminalSettingsAccessAddDeviceRoute
  '/_terminal/settings/categories/$catalogCategoryId': typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  '/_terminal/settings/categories/new': typeof TerminalSettingsCategoriesNewRoute
  '/_terminal/settings/items/$catalogItemId': typeof TerminalSettingsItemsCatalogItemIdRoute
  '/_terminal/settings/items/new': typeof TerminalSettingsItemsNewRoute
  '/_terminal/settings/payment-accounts/card-switchio': typeof TerminalSettingsPaymentAccountsCardSwitchioRoute
  '/_terminal/settings/payment-accounts/iban': typeof TerminalSettingsPaymentAccountsIbanRouteWithChildren
  '/_terminal/settings/payment-accounts/spark': typeof TerminalSettingsPaymentAccountsSparkRouteWithChildren
  '/_terminal/settings/tables/$tableId': typeof TerminalSettingsTablesTableIdRoute
  '/_terminal/settings/tables/new': typeof TerminalSettingsTablesNewRoute
  '/_terminal/settings/about/': typeof TerminalSettingsAboutIndexRoute
  '/_terminal/settings/accounts/': typeof TerminalSettingsAccountsIndexRoute
  '/_terminal/settings/categories/': typeof TerminalSettingsCategoriesIndexRoute
  '/_terminal/settings/items/': typeof TerminalSettingsItemsIndexRoute
  '/_terminal/settings/payment-accounts/': typeof TerminalSettingsPaymentAccountsIndexRoute
  '/_terminal/settings/tables/': typeof TerminalSettingsTablesIndexRoute
  '/_terminal/settings/payment-accounts/iban/fio-plugin': typeof TerminalSettingsPaymentAccountsIbanFioPluginRoute
  '/_terminal/settings/payment-accounts/spark/transactions': typeof TerminalSettingsPaymentAccountsSparkTransactionsRoute
  '/_terminal/settings/payment-accounts/spark/withdrawals': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRouteWithChildren
  '/_terminal/settings/payment-accounts/iban/': typeof TerminalSettingsPaymentAccountsIbanIndexRoute
  '/_terminal/settings/payment-accounts/spark/': typeof TerminalSettingsPaymentAccountsSparkIndexRoute
  '/_terminal/settings/payment-accounts/spark/withdrawals/$withdrawalId': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute
  '/_terminal/settings/payment-accounts/spark/withdrawals/new': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute
  '/_terminal/settings/payment-accounts/spark/withdrawals/': typeof TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/onboarding'
    | '/restore-account'
    | '/activity'
    | '/bill'
    | '/settings'
    | '/activity/$paymentId'
    | '/activity/bills'
    | '/payment/tip'
    | '/payment/$paymentId'
    | '/settings/about'
    | '/settings/access'
    | '/settings/accounts'
    | '/settings/assistant'
    | '/settings/categories'
    | '/settings/debug-console'
    | '/settings/donations'
    | '/settings/donations-invoice'
    | '/settings/eet'
    | '/settings/evolu-export'
    | '/settings/home-screen'
    | '/settings/items'
    | '/settings/language'
    | '/settings/legal-entity'
    | '/settings/payment-accounts'
    | '/settings/payment-number-series'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/support'
    | '/settings/tables'
    | '/settings/tax-rates'
    | '/settings/theme'
    | '/settings/tips'
    | '/settings/'
    | '/activity/bills/$billId'
    | '/settings/about/privacy'
    | '/settings/about/terms'
    | '/settings/access/add-device'
    | '/settings/categories/$catalogCategoryId'
    | '/settings/categories/new'
    | '/settings/items/$catalogItemId'
    | '/settings/items/new'
    | '/settings/payment-accounts/card-switchio'
    | '/settings/payment-accounts/iban'
    | '/settings/payment-accounts/spark'
    | '/settings/tables/$tableId'
    | '/settings/tables/new'
    | '/settings/about/'
    | '/settings/accounts/'
    | '/settings/categories/'
    | '/settings/items/'
    | '/settings/payment-accounts/'
    | '/settings/tables/'
    | '/settings/payment-accounts/iban/fio-plugin'
    | '/settings/payment-accounts/spark/transactions'
    | '/settings/payment-accounts/spark/withdrawals'
    | '/settings/payment-accounts/iban/'
    | '/settings/payment-accounts/spark/'
    | '/settings/payment-accounts/spark/withdrawals/$withdrawalId'
    | '/settings/payment-accounts/spark/withdrawals/new'
    | '/settings/payment-accounts/spark/withdrawals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/onboarding'
    | '/restore-account'
    | '/activity'
    | '/bill'
    | '/'
    | '/activity/$paymentId'
    | '/activity/bills'
    | '/payment/tip'
    | '/payment/$paymentId'
    | '/settings/access'
    | '/settings/assistant'
    | '/settings/debug-console'
    | '/settings/donations'
    | '/settings/donations-invoice'
    | '/settings/eet'
    | '/settings/evolu-export'
    | '/settings/home-screen'
    | '/settings/language'
    | '/settings/legal-entity'
    | '/settings/payment-number-series'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/support'
    | '/settings/tax-rates'
    | '/settings/theme'
    | '/settings/tips'
    | '/settings'
    | '/activity/bills/$billId'
    | '/settings/about/privacy'
    | '/settings/about/terms'
    | '/settings/access/add-device'
    | '/settings/categories/$catalogCategoryId'
    | '/settings/categories/new'
    | '/settings/items/$catalogItemId'
    | '/settings/items/new'
    | '/settings/payment-accounts/card-switchio'
    | '/settings/tables/$tableId'
    | '/settings/tables/new'
    | '/settings/about'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/items'
    | '/settings/payment-accounts'
    | '/settings/tables'
    | '/settings/payment-accounts/iban/fio-plugin'
    | '/settings/payment-accounts/spark/transactions'
    | '/settings/payment-accounts/iban'
    | '/settings/payment-accounts/spark'
    | '/settings/payment-accounts/spark/withdrawals/$withdrawalId'
    | '/settings/payment-accounts/spark/withdrawals/new'
    | '/settings/payment-accounts/spark/withdrawals'
  id:
    | '__root__'
    | '/_terminal'
    | '/error'
    | '/onboarding'
    | '/restore-account'
    | '/_terminal/activity'
    | '/_terminal/bill'
    | '/_terminal/settings'
    | '/_terminal/'
    | '/_terminal/activity_/$paymentId'
    | '/_terminal/activity_/bills'
    | '/_terminal/payment/tip'
    | '/_terminal/payment_/$paymentId'
    | '/_terminal/settings/about'
    | '/_terminal/settings/access'
    | '/_terminal/settings/accounts'
    | '/_terminal/settings/assistant'
    | '/_terminal/settings/categories'
    | '/_terminal/settings/debug-console'
    | '/_terminal/settings/donations'
    | '/_terminal/settings/donations-invoice'
    | '/_terminal/settings/eet'
    | '/_terminal/settings/evolu-export'
    | '/_terminal/settings/home-screen'
    | '/_terminal/settings/items'
    | '/_terminal/settings/language'
    | '/_terminal/settings/legal-entity'
    | '/_terminal/settings/payment-accounts'
    | '/_terminal/settings/payment-number-series'
    | '/_terminal/settings/profile'
    | '/_terminal/settings/security'
    | '/_terminal/settings/support'
    | '/_terminal/settings/tables'
    | '/_terminal/settings/tax-rates'
    | '/_terminal/settings/theme'
    | '/_terminal/settings/tips'
    | '/_terminal/settings/'
    | '/_terminal/activity_/bills_/$billId'
    | '/_terminal/settings/about/privacy'
    | '/_terminal/settings/about/terms'
    | '/_terminal/settings/access_/add-device'
    | '/_terminal/settings/categories/$catalogCategoryId'
    | '/_terminal/settings/categories/new'
    | '/_terminal/settings/items/$catalogItemId'
    | '/_terminal/settings/items/new'
    | '/_terminal/settings/payment-accounts/card-switchio'
    | '/_terminal/settings/payment-accounts/iban'
    | '/_terminal/settings/payment-accounts/spark'
    | '/_terminal/settings/tables/$tableId'
    | '/_terminal/settings/tables/new'
    | '/_terminal/settings/about/'
    | '/_terminal/settings/accounts/'
    | '/_terminal/settings/categories/'
    | '/_terminal/settings/items/'
    | '/_terminal/settings/payment-accounts/'
    | '/_terminal/settings/tables/'
    | '/_terminal/settings/payment-accounts/iban/fio-plugin'
    | '/_terminal/settings/payment-accounts/spark/transactions'
    | '/_terminal/settings/payment-accounts/spark/withdrawals'
    | '/_terminal/settings/payment-accounts/iban/'
    | '/_terminal/settings/payment-accounts/spark/'
    | '/_terminal/settings/payment-accounts/spark/withdrawals/$withdrawalId'
    | '/_terminal/settings/payment-accounts/spark/withdrawals/new'
    | '/_terminal/settings/payment-accounts/spark/withdrawals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TerminalRoute: typeof TerminalRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  OnboardingRoute: typeof OnboardingRoute
  RestoreAccountRoute: typeof RestoreAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_terminal': {
      id: '/_terminal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore-account': {
      id: '/restore-account'
      path: '/restore-account'
      fullPath: '/restore-account'
      preLoaderRoute: typeof RestoreAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal/': {
      id: '/_terminal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity': {
      id: '/_terminal/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof TerminalActivityRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/bill': {
      id: '/_terminal/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof TerminalBillRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings': {
      id: '/_terminal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TerminalSettingsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity_/$paymentId': {
      id: '/_terminal/activity_/$paymentId'
      path: '/activity/$paymentId'
      fullPath: '/activity/$paymentId'
      preLoaderRoute: typeof TerminalActivityPaymentIdRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/activity_/bills': {
      id: '/_terminal/activity_/bills'
      path: '/activity/bills'
      fullPath: '/activity/bills'
      preLoaderRoute: typeof TerminalActivityBillsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/payment/tip': {
      id: '/_terminal/payment/tip'
      path: '/payment/tip'
      fullPath: '/payment/tip'
      preLoaderRoute: typeof TerminalPaymentTipRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/payment_/$paymentId': {
      id: '/_terminal/payment_/$paymentId'
      path: '/payment/$paymentId'
      fullPath: '/payment/$paymentId'
      preLoaderRoute: typeof TerminalPaymentPaymentIdRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings/': {
      id: '/_terminal/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof TerminalSettingsIndexRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/about': {
      id: '/_terminal/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof TerminalSettingsAboutRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/access': {
      id: '/_terminal/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof TerminalSettingsAccessRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/accounts': {
      id: '/_terminal/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof TerminalSettingsAccountsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/assistant': {
      id: '/_terminal/settings/assistant'
      path: '/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof TerminalSettingsAssistantRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/categories': {
      id: '/_terminal/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof TerminalSettingsCategoriesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/debug-console': {
      id: '/_terminal/settings/debug-console'
      path: '/debug-console'
      fullPath: '/settings/debug-console'
      preLoaderRoute: typeof TerminalSettingsDebugConsoleRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/donations': {
      id: '/_terminal/settings/donations'
      path: '/donations'
      fullPath: '/settings/donations'
      preLoaderRoute: typeof TerminalSettingsDonationsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/donations-invoice': {
      id: '/_terminal/settings/donations-invoice'
      path: '/donations-invoice'
      fullPath: '/settings/donations-invoice'
      preLoaderRoute: typeof TerminalSettingsDonationsInvoiceRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/eet': {
      id: '/_terminal/settings/eet'
      path: '/eet'
      fullPath: '/settings/eet'
      preLoaderRoute: typeof TerminalSettingsEetRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/evolu-export': {
      id: '/_terminal/settings/evolu-export'
      path: '/evolu-export'
      fullPath: '/settings/evolu-export'
      preLoaderRoute: typeof TerminalSettingsEvoluExportRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/home-screen': {
      id: '/_terminal/settings/home-screen'
      path: '/home-screen'
      fullPath: '/settings/home-screen'
      preLoaderRoute: typeof TerminalSettingsHomeScreenRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/items': {
      id: '/_terminal/settings/items'
      path: '/items'
      fullPath: '/settings/items'
      preLoaderRoute: typeof TerminalSettingsItemsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/language': {
      id: '/_terminal/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof TerminalSettingsLanguageRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/legal-entity': {
      id: '/_terminal/settings/legal-entity'
      path: '/legal-entity'
      fullPath: '/settings/legal-entity'
      preLoaderRoute: typeof TerminalSettingsLegalEntityRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/payment-accounts': {
      id: '/_terminal/settings/payment-accounts'
      path: '/payment-accounts'
      fullPath: '/settings/payment-accounts'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/payment-number-series': {
      id: '/_terminal/settings/payment-number-series'
      path: '/payment-number-series'
      fullPath: '/settings/payment-number-series'
      preLoaderRoute: typeof TerminalSettingsPaymentNumberSeriesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/profile': {
      id: '/_terminal/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof TerminalSettingsProfileRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/security': {
      id: '/_terminal/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof TerminalSettingsSecurityRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/support': {
      id: '/_terminal/settings/support'
      path: '/support'
      fullPath: '/settings/support'
      preLoaderRoute: typeof TerminalSettingsSupportRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/tables': {
      id: '/_terminal/settings/tables'
      path: '/tables'
      fullPath: '/settings/tables'
      preLoaderRoute: typeof TerminalSettingsTablesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/tax-rates': {
      id: '/_terminal/settings/tax-rates'
      path: '/tax-rates'
      fullPath: '/settings/tax-rates'
      preLoaderRoute: typeof TerminalSettingsTaxRatesRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/theme': {
      id: '/_terminal/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof TerminalSettingsThemeRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/tips': {
      id: '/_terminal/settings/tips'
      path: '/tips'
      fullPath: '/settings/tips'
      preLoaderRoute: typeof TerminalSettingsTipsRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/activity_/bills_/$billId': {
      id: '/_terminal/activity_/bills_/$billId'
      path: '/activity/bills/$billId'
      fullPath: '/activity/bills/$billId'
      preLoaderRoute: typeof TerminalActivityBillsBillIdRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings/about/': {
      id: '/_terminal/settings/about/'
      path: '/'
      fullPath: '/settings/about/'
      preLoaderRoute: typeof TerminalSettingsAboutIndexRouteImport
      parentRoute: typeof TerminalSettingsAboutRoute
    }
    '/_terminal/settings/about/privacy': {
      id: '/_terminal/settings/about/privacy'
      path: '/privacy'
      fullPath: '/settings/about/privacy'
      preLoaderRoute: typeof TerminalSettingsAboutPrivacyRouteImport
      parentRoute: typeof TerminalSettingsAboutRoute
    }
    '/_terminal/settings/about/terms': {
      id: '/_terminal/settings/about/terms'
      path: '/terms'
      fullPath: '/settings/about/terms'
      preLoaderRoute: typeof TerminalSettingsAboutTermsRouteImport
      parentRoute: typeof TerminalSettingsAboutRoute
    }
    '/_terminal/settings/access_/add-device': {
      id: '/_terminal/settings/access_/add-device'
      path: '/access/add-device'
      fullPath: '/settings/access/add-device'
      preLoaderRoute: typeof TerminalSettingsAccessAddDeviceRouteImport
      parentRoute: typeof TerminalSettingsRoute
    }
    '/_terminal/settings/accounts/': {
      id: '/_terminal/settings/accounts/'
      path: '/'
      fullPath: '/settings/accounts/'
      preLoaderRoute: typeof TerminalSettingsAccountsIndexRouteImport
      parentRoute: typeof TerminalSettingsAccountsRoute
    }
    '/_terminal/settings/categories/': {
      id: '/_terminal/settings/categories/'
      path: '/'
      fullPath: '/settings/categories/'
      preLoaderRoute: typeof TerminalSettingsCategoriesIndexRouteImport
      parentRoute: typeof TerminalSettingsCategoriesRoute
    }
    '/_terminal/settings/categories/$catalogCategoryId': {
      id: '/_terminal/settings/categories/$catalogCategoryId'
      path: '/$catalogCategoryId'
      fullPath: '/settings/categories/$catalogCategoryId'
      preLoaderRoute: typeof TerminalSettingsCategoriesCatalogCategoryIdRouteImport
      parentRoute: typeof TerminalSettingsCategoriesRoute
    }
    '/_terminal/settings/categories/new': {
      id: '/_terminal/settings/categories/new'
      path: '/new'
      fullPath: '/settings/categories/new'
      preLoaderRoute: typeof TerminalSettingsCategoriesNewRouteImport
      parentRoute: typeof TerminalSettingsCategoriesRoute
    }
    '/_terminal/settings/items/': {
      id: '/_terminal/settings/items/'
      path: '/'
      fullPath: '/settings/items/'
      preLoaderRoute: typeof TerminalSettingsItemsIndexRouteImport
      parentRoute: typeof TerminalSettingsItemsRoute
    }
    '/_terminal/settings/items/$catalogItemId': {
      id: '/_terminal/settings/items/$catalogItemId'
      path: '/$catalogItemId'
      fullPath: '/settings/items/$catalogItemId'
      preLoaderRoute: typeof TerminalSettingsItemsCatalogItemIdRouteImport
      parentRoute: typeof TerminalSettingsItemsRoute
    }
    '/_terminal/settings/items/new': {
      id: '/_terminal/settings/items/new'
      path: '/new'
      fullPath: '/settings/items/new'
      preLoaderRoute: typeof TerminalSettingsItemsNewRouteImport
      parentRoute: typeof TerminalSettingsItemsRoute
    }
    '/_terminal/settings/payment-accounts/': {
      id: '/_terminal/settings/payment-accounts/'
      path: '/'
      fullPath: '/settings/payment-accounts/'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsIndexRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsRoute
    }
    '/_terminal/settings/payment-accounts/card-switchio': {
      id: '/_terminal/settings/payment-accounts/card-switchio'
      path: '/card-switchio'
      fullPath: '/settings/payment-accounts/card-switchio'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsCardSwitchioRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsRoute
    }
    '/_terminal/settings/payment-accounts/iban': {
      id: '/_terminal/settings/payment-accounts/iban'
      path: '/iban'
      fullPath: '/settings/payment-accounts/iban'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsIbanRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsRoute
    }
    '/_terminal/settings/payment-accounts/spark': {
      id: '/_terminal/settings/payment-accounts/spark'
      path: '/spark'
      fullPath: '/settings/payment-accounts/spark'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsRoute
    }
    '/_terminal/settings/tables/': {
      id: '/_terminal/settings/tables/'
      path: '/'
      fullPath: '/settings/tables/'
      preLoaderRoute: typeof TerminalSettingsTablesIndexRouteImport
      parentRoute: typeof TerminalSettingsTablesRoute
    }
    '/_terminal/settings/tables/$tableId': {
      id: '/_terminal/settings/tables/$tableId'
      path: '/$tableId'
      fullPath: '/settings/tables/$tableId'
      preLoaderRoute: typeof TerminalSettingsTablesTableIdRouteImport
      parentRoute: typeof TerminalSettingsTablesRoute
    }
    '/_terminal/settings/tables/new': {
      id: '/_terminal/settings/tables/new'
      path: '/new'
      fullPath: '/settings/tables/new'
      preLoaderRoute: typeof TerminalSettingsTablesNewRouteImport
      parentRoute: typeof TerminalSettingsTablesRoute
    }
    '/_terminal/settings/payment-accounts/iban/': {
      id: '/_terminal/settings/payment-accounts/iban/'
      path: '/'
      fullPath: '/settings/payment-accounts/iban/'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsIbanIndexRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsIbanRoute
    }
    '/_terminal/settings/payment-accounts/iban/fio-plugin': {
      id: '/_terminal/settings/payment-accounts/iban/fio-plugin'
      path: '/fio-plugin'
      fullPath: '/settings/payment-accounts/iban/fio-plugin'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsIbanFioPluginRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsIbanRoute
    }
    '/_terminal/settings/payment-accounts/spark/': {
      id: '/_terminal/settings/payment-accounts/spark/'
      path: '/'
      fullPath: '/settings/payment-accounts/spark/'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkIndexRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsSparkRoute
    }
    '/_terminal/settings/payment-accounts/spark/transactions': {
      id: '/_terminal/settings/payment-accounts/spark/transactions'
      path: '/transactions'
      fullPath: '/settings/payment-accounts/spark/transactions'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkTransactionsRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsSparkRoute
    }
    '/_terminal/settings/payment-accounts/spark/withdrawals': {
      id: '/_terminal/settings/payment-accounts/spark/withdrawals'
      path: '/withdrawals'
      fullPath: '/settings/payment-accounts/spark/withdrawals'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsSparkRoute
    }
    '/_terminal/settings/payment-accounts/spark/withdrawals/': {
      id: '/_terminal/settings/payment-accounts/spark/withdrawals/'
      path: '/'
      fullPath: '/settings/payment-accounts/spark/withdrawals/'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRoute
    }
    '/_terminal/settings/payment-accounts/spark/withdrawals/$withdrawalId': {
      id: '/_terminal/settings/payment-accounts/spark/withdrawals/$withdrawalId'
      path: '/$withdrawalId'
      fullPath: '/settings/payment-accounts/spark/withdrawals/$withdrawalId'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRoute
    }
    '/_terminal/settings/payment-accounts/spark/withdrawals/new': {
      id: '/_terminal/settings/payment-accounts/spark/withdrawals/new'
      path: '/new'
      fullPath: '/settings/payment-accounts/spark/withdrawals/new'
      preLoaderRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsNewRouteImport
      parentRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRoute
    }
  }
}

interface TerminalSettingsAboutRouteChildren {
  TerminalSettingsAboutPrivacyRoute: typeof TerminalSettingsAboutPrivacyRoute
  TerminalSettingsAboutTermsRoute: typeof TerminalSettingsAboutTermsRoute
  TerminalSettingsAboutIndexRoute: typeof TerminalSettingsAboutIndexRoute
}

const TerminalSettingsAboutRouteChildren: TerminalSettingsAboutRouteChildren = {
  TerminalSettingsAboutPrivacyRoute: TerminalSettingsAboutPrivacyRoute,
  TerminalSettingsAboutTermsRoute: TerminalSettingsAboutTermsRoute,
  TerminalSettingsAboutIndexRoute: TerminalSettingsAboutIndexRoute,
}

const TerminalSettingsAboutRouteWithChildren =
  TerminalSettingsAboutRoute._addFileChildren(
    TerminalSettingsAboutRouteChildren,
  )

interface TerminalSettingsAccountsRouteChildren {
  TerminalSettingsAccountsIndexRoute: typeof TerminalSettingsAccountsIndexRoute
}

const TerminalSettingsAccountsRouteChildren: TerminalSettingsAccountsRouteChildren =
  {
    TerminalSettingsAccountsIndexRoute: TerminalSettingsAccountsIndexRoute,
  }

const TerminalSettingsAccountsRouteWithChildren =
  TerminalSettingsAccountsRoute._addFileChildren(
    TerminalSettingsAccountsRouteChildren,
  )

interface TerminalSettingsCategoriesRouteChildren {
  TerminalSettingsCategoriesCatalogCategoryIdRoute: typeof TerminalSettingsCategoriesCatalogCategoryIdRoute
  TerminalSettingsCategoriesNewRoute: typeof TerminalSettingsCategoriesNewRoute
  TerminalSettingsCategoriesIndexRoute: typeof TerminalSettingsCategoriesIndexRoute
}

const TerminalSettingsCategoriesRouteChildren: TerminalSettingsCategoriesRouteChildren =
  {
    TerminalSettingsCategoriesCatalogCategoryIdRoute:
      TerminalSettingsCategoriesCatalogCategoryIdRoute,
    TerminalSettingsCategoriesNewRoute: TerminalSettingsCategoriesNewRoute,
    TerminalSettingsCategoriesIndexRoute: TerminalSettingsCategoriesIndexRoute,
  }

const TerminalSettingsCategoriesRouteWithChildren =
  TerminalSettingsCategoriesRoute._addFileChildren(
    TerminalSettingsCategoriesRouteChildren,
  )

interface TerminalSettingsItemsRouteChildren {
  TerminalSettingsItemsCatalogItemIdRoute: typeof TerminalSettingsItemsCatalogItemIdRoute
  TerminalSettingsItemsNewRoute: typeof TerminalSettingsItemsNewRoute
  TerminalSettingsItemsIndexRoute: typeof TerminalSettingsItemsIndexRoute
}

const TerminalSettingsItemsRouteChildren: TerminalSettingsItemsRouteChildren = {
  TerminalSettingsItemsCatalogItemIdRoute:
    TerminalSettingsItemsCatalogItemIdRoute,
  TerminalSettingsItemsNewRoute: TerminalSettingsItemsNewRoute,
  TerminalSettingsItemsIndexRoute: TerminalSettingsItemsIndexRoute,
}

const TerminalSettingsItemsRouteWithChildren =
  TerminalSettingsItemsRoute._addFileChildren(
    TerminalSettingsItemsRouteChildren,
  )

interface TerminalSettingsPaymentAccountsIbanRouteChildren {
  TerminalSettingsPaymentAccountsIbanFioPluginRoute: typeof TerminalSettingsPaymentAccountsIbanFioPluginRoute
  TerminalSettingsPaymentAccountsIbanIndexRoute: typeof TerminalSettingsPaymentAccountsIbanIndexRoute
}

const TerminalSettingsPaymentAccountsIbanRouteChildren: TerminalSettingsPaymentAccountsIbanRouteChildren =
  {
    TerminalSettingsPaymentAccountsIbanFioPluginRoute:
      TerminalSettingsPaymentAccountsIbanFioPluginRoute,
    TerminalSettingsPaymentAccountsIbanIndexRoute:
      TerminalSettingsPaymentAccountsIbanIndexRoute,
  }

const TerminalSettingsPaymentAccountsIbanRouteWithChildren =
  TerminalSettingsPaymentAccountsIbanRoute._addFileChildren(
    TerminalSettingsPaymentAccountsIbanRouteChildren,
  )

interface TerminalSettingsPaymentAccountsSparkWithdrawalsRouteChildren {
  TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute
  TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute
  TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute
}

const TerminalSettingsPaymentAccountsSparkWithdrawalsRouteChildren: TerminalSettingsPaymentAccountsSparkWithdrawalsRouteChildren =
  {
    TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute:
      TerminalSettingsPaymentAccountsSparkWithdrawalsWithdrawalIdRoute,
    TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute:
      TerminalSettingsPaymentAccountsSparkWithdrawalsNewRoute,
    TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute:
      TerminalSettingsPaymentAccountsSparkWithdrawalsIndexRoute,
  }

const TerminalSettingsPaymentAccountsSparkWithdrawalsRouteWithChildren =
  TerminalSettingsPaymentAccountsSparkWithdrawalsRoute._addFileChildren(
    TerminalSettingsPaymentAccountsSparkWithdrawalsRouteChildren,
  )

interface TerminalSettingsPaymentAccountsSparkRouteChildren {
  TerminalSettingsPaymentAccountsSparkTransactionsRoute: typeof TerminalSettingsPaymentAccountsSparkTransactionsRoute
  TerminalSettingsPaymentAccountsSparkWithdrawalsRoute: typeof TerminalSettingsPaymentAccountsSparkWithdrawalsRouteWithChildren
  TerminalSettingsPaymentAccountsSparkIndexRoute: typeof TerminalSettingsPaymentAccountsSparkIndexRoute
}

const TerminalSettingsPaymentAccountsSparkRouteChildren: TerminalSettingsPaymentAccountsSparkRouteChildren =
  {
    TerminalSettingsPaymentAccountsSparkTransactionsRoute:
      TerminalSettingsPaymentAccountsSparkTransactionsRoute,
    TerminalSettingsPaymentAccountsSparkWithdrawalsRoute:
      TerminalSettingsPaymentAccountsSparkWithdrawalsRouteWithChildren,
    TerminalSettingsPaymentAccountsSparkIndexRoute:
      TerminalSettingsPaymentAccountsSparkIndexRoute,
  }

const TerminalSettingsPaymentAccountsSparkRouteWithChildren =
  TerminalSettingsPaymentAccountsSparkRoute._addFileChildren(
    TerminalSettingsPaymentAccountsSparkRouteChildren,
  )

interface TerminalSettingsPaymentAccountsRouteChildren {
  TerminalSettingsPaymentAccountsCardSwitchioRoute: typeof TerminalSettingsPaymentAccountsCardSwitchioRoute
  TerminalSettingsPaymentAccountsIbanRoute: typeof TerminalSettingsPaymentAccountsIbanRouteWithChildren
  TerminalSettingsPaymentAccountsSparkRoute: typeof TerminalSettingsPaymentAccountsSparkRouteWithChildren
  TerminalSettingsPaymentAccountsIndexRoute: typeof TerminalSettingsPaymentAccountsIndexRoute
}

const TerminalSettingsPaymentAccountsRouteChildren: TerminalSettingsPaymentAccountsRouteChildren =
  {
    TerminalSettingsPaymentAccountsCardSwitchioRoute:
      TerminalSettingsPaymentAccountsCardSwitchioRoute,
    TerminalSettingsPaymentAccountsIbanRoute:
      TerminalSettingsPaymentAccountsIbanRouteWithChildren,
    TerminalSettingsPaymentAccountsSparkRoute:
      TerminalSettingsPaymentAccountsSparkRouteWithChildren,
    TerminalSettingsPaymentAccountsIndexRoute:
      TerminalSettingsPaymentAccountsIndexRoute,
  }

const TerminalSettingsPaymentAccountsRouteWithChildren =
  TerminalSettingsPaymentAccountsRoute._addFileChildren(
    TerminalSettingsPaymentAccountsRouteChildren,
  )

interface TerminalSettingsTablesRouteChildren {
  TerminalSettingsTablesTableIdRoute: typeof TerminalSettingsTablesTableIdRoute
  TerminalSettingsTablesNewRoute: typeof TerminalSettingsTablesNewRoute
  TerminalSettingsTablesIndexRoute: typeof TerminalSettingsTablesIndexRoute
}

const TerminalSettingsTablesRouteChildren: TerminalSettingsTablesRouteChildren =
  {
    TerminalSettingsTablesTableIdRoute: TerminalSettingsTablesTableIdRoute,
    TerminalSettingsTablesNewRoute: TerminalSettingsTablesNewRoute,
    TerminalSettingsTablesIndexRoute: TerminalSettingsTablesIndexRoute,
  }

const TerminalSettingsTablesRouteWithChildren =
  TerminalSettingsTablesRoute._addFileChildren(
    TerminalSettingsTablesRouteChildren,
  )

interface TerminalSettingsRouteChildren {
  TerminalSettingsAboutRoute: typeof TerminalSettingsAboutRouteWithChildren
  TerminalSettingsAccessRoute: typeof TerminalSettingsAccessRoute
  TerminalSettingsAccountsRoute: typeof TerminalSettingsAccountsRouteWithChildren
  TerminalSettingsAssistantRoute: typeof TerminalSettingsAssistantRoute
  TerminalSettingsCategoriesRoute: typeof TerminalSettingsCategoriesRouteWithChildren
  TerminalSettingsDebugConsoleRoute: typeof TerminalSettingsDebugConsoleRoute
  TerminalSettingsDonationsRoute: typeof TerminalSettingsDonationsRoute
  TerminalSettingsDonationsInvoiceRoute: typeof TerminalSettingsDonationsInvoiceRoute
  TerminalSettingsEetRoute: typeof TerminalSettingsEetRoute
  TerminalSettingsEvoluExportRoute: typeof TerminalSettingsEvoluExportRoute
  TerminalSettingsHomeScreenRoute: typeof TerminalSettingsHomeScreenRoute
  TerminalSettingsItemsRoute: typeof TerminalSettingsItemsRouteWithChildren
  TerminalSettingsLanguageRoute: typeof TerminalSettingsLanguageRoute
  TerminalSettingsLegalEntityRoute: typeof TerminalSettingsLegalEntityRoute
  TerminalSettingsPaymentAccountsRoute: typeof TerminalSettingsPaymentAccountsRouteWithChildren
  TerminalSettingsPaymentNumberSeriesRoute: typeof TerminalSettingsPaymentNumberSeriesRoute
  TerminalSettingsProfileRoute: typeof TerminalSettingsProfileRoute
  TerminalSettingsSecurityRoute: typeof TerminalSettingsSecurityRoute
  TerminalSettingsSupportRoute: typeof TerminalSettingsSupportRoute
  TerminalSettingsTablesRoute: typeof TerminalSettingsTablesRouteWithChildren
  TerminalSettingsTaxRatesRoute: typeof TerminalSettingsTaxRatesRoute
  TerminalSettingsThemeRoute: typeof TerminalSettingsThemeRoute
  TerminalSettingsTipsRoute: typeof TerminalSettingsTipsRoute
  TerminalSettingsIndexRoute: typeof TerminalSettingsIndexRoute
  TerminalSettingsAccessAddDeviceRoute: typeof TerminalSettingsAccessAddDeviceRoute
}

const TerminalSettingsRouteChildren: TerminalSettingsRouteChildren = {
  TerminalSettingsAboutRoute: TerminalSettingsAboutRouteWithChildren,
  TerminalSettingsAccessRoute: TerminalSettingsAccessRoute,
  TerminalSettingsAccountsRoute: TerminalSettingsAccountsRouteWithChildren,
  TerminalSettingsAssistantRoute: TerminalSettingsAssistantRoute,
  TerminalSettingsCategoriesRoute: TerminalSettingsCategoriesRouteWithChildren,
  TerminalSettingsDebugConsoleRoute: TerminalSettingsDebugConsoleRoute,
  TerminalSettingsDonationsRoute: TerminalSettingsDonationsRoute,
  TerminalSettingsDonationsInvoiceRoute: TerminalSettingsDonationsInvoiceRoute,
  TerminalSettingsEetRoute: TerminalSettingsEetRoute,
  TerminalSettingsEvoluExportRoute: TerminalSettingsEvoluExportRoute,
  TerminalSettingsHomeScreenRoute: TerminalSettingsHomeScreenRoute,
  TerminalSettingsItemsRoute: TerminalSettingsItemsRouteWithChildren,
  TerminalSettingsLanguageRoute: TerminalSettingsLanguageRoute,
  TerminalSettingsLegalEntityRoute: TerminalSettingsLegalEntityRoute,
  TerminalSettingsPaymentAccountsRoute:
    TerminalSettingsPaymentAccountsRouteWithChildren,
  TerminalSettingsPaymentNumberSeriesRoute:
    TerminalSettingsPaymentNumberSeriesRoute,
  TerminalSettingsProfileRoute: TerminalSettingsProfileRoute,
  TerminalSettingsSecurityRoute: TerminalSettingsSecurityRoute,
  TerminalSettingsSupportRoute: TerminalSettingsSupportRoute,
  TerminalSettingsTablesRoute: TerminalSettingsTablesRouteWithChildren,
  TerminalSettingsTaxRatesRoute: TerminalSettingsTaxRatesRoute,
  TerminalSettingsThemeRoute: TerminalSettingsThemeRoute,
  TerminalSettingsTipsRoute: TerminalSettingsTipsRoute,
  TerminalSettingsIndexRoute: TerminalSettingsIndexRoute,
  TerminalSettingsAccessAddDeviceRoute: TerminalSettingsAccessAddDeviceRoute,
}

const TerminalSettingsRouteWithChildren =
  TerminalSettingsRoute._addFileChildren(TerminalSettingsRouteChildren)

interface TerminalRouteChildren {
  TerminalActivityRoute: typeof TerminalActivityRoute
  TerminalBillRoute: typeof TerminalBillRoute
  TerminalSettingsRoute: typeof TerminalSettingsRouteWithChildren
  TerminalIndexRoute: typeof TerminalIndexRoute
  TerminalActivityPaymentIdRoute: typeof TerminalActivityPaymentIdRoute
  TerminalActivityBillsRoute: typeof TerminalActivityBillsRoute
  TerminalPaymentTipRoute: typeof TerminalPaymentTipRoute
  TerminalPaymentPaymentIdRoute: typeof TerminalPaymentPaymentIdRoute
  TerminalActivityBillsBillIdRoute: typeof TerminalActivityBillsBillIdRoute
}

const TerminalRouteChildren: TerminalRouteChildren = {
  TerminalActivityRoute: TerminalActivityRoute,
  TerminalBillRoute: TerminalBillRoute,
  TerminalSettingsRoute: TerminalSettingsRouteWithChildren,
  TerminalIndexRoute: TerminalIndexRoute,
  TerminalActivityPaymentIdRoute: TerminalActivityPaymentIdRoute,
  TerminalActivityBillsRoute: TerminalActivityBillsRoute,
  TerminalPaymentTipRoute: TerminalPaymentTipRoute,
  TerminalPaymentPaymentIdRoute: TerminalPaymentPaymentIdRoute,
  TerminalActivityBillsBillIdRoute: TerminalActivityBillsBillIdRoute,
}

const TerminalRouteWithChildren = TerminalRoute._addFileChildren(
  TerminalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TerminalRoute: TerminalRouteWithChildren,
  ErrorRoute: ErrorRoute,
  OnboardingRoute: OnboardingRoute,
  RestoreAccountRoute: RestoreAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
